import { chapter, subject } from './builder';

/**
 * The commerce and humanities subjects of CBSE classes 11 and 12.
 *
 * Shared between streams the same way the science subjects are: class 12
 * Economics is one syllabus whether a student reads it alongside Accountancy or
 * alongside Political Science.
 */

// ---------------------------------------------------------------------------
// Commerce — class 11
// ---------------------------------------------------------------------------

export const class11Accountancy = subject(
  'Accountancy',
  chapter(
    'Introduction to Accounting',
    'Meaning and objectives of accounting',
    'Users of accounting information',
    'Qualitative characteristics of accounting information',
    'Branches of accounting',
    'Basic accounting terms',
  ),
  chapter(
    'Theory Base of Accounting',
    'Generally accepted accounting principles',
    'Basic accounting concepts',
    'Systems of accounting',
    'Basis of accounting',
    'Accounting standards and IFRS',
    'Goods and Services Tax',
  ),
  chapter(
    'Recording of Transactions — I',
    'Business transactions and source documents',
    'Accounting equation',
    'Using debit and credit',
    'Books of original entry',
    'The ledger',
  ),
  chapter(
    'Recording of Transactions — II',
    'Cash book',
    'Purchases and sales journals',
    'Purchases and sales return journals',
    'Journal proper',
    'Balancing the accounts',
  ),
  chapter(
    'Bank Reconciliation Statement',
    'Need for reconciliation',
    'Preparation of a bank reconciliation statement',
    'Adjusted or amended cash book',
  ),
  chapter(
    'Trial Balance and Rectification of Errors',
    'Meaning and objectives of a trial balance',
    'Preparation of a trial balance',
    'Classification of errors',
    'Searching for errors',
    'Rectification of errors',
    'Suspense account',
  ),
  chapter(
    'Depreciation, Provisions and Reserves',
    'Meaning and causes of depreciation',
    'Methods of calculating depreciation',
    'Accounting treatment of depreciation',
    'Disposal of an asset',
    'Provisions and reserves',
  ),
  chapter(
    'Financial Statements — I',
    'Stakeholders and their information requirements',
    'Trading and profit and loss account',
    'Balance sheet',
    'Operating profit',
  ),
  chapter(
    'Financial Statements — II',
    'Need for adjustments',
    'Closing stock',
    'Outstanding and prepaid expenses',
    'Accrued and unearned income',
    'Depreciation and bad debts',
    'Provision for doubtful debts',
  ),
  chapter(
    'Accounts from Incomplete Records',
    'Features of incomplete records',
    'Ascertainment of profit and loss',
    'Preparing a statement of affairs',
  ),
  chapter(
    'Computerised Accounting System',
    'Concept of a computerised accounting system',
    'Comparison with manual accounting',
    'Sourcing of an accounting system',
  ),
);

export const class11BusinessStudies = subject(
  'Business Studies',
  chapter(
    'Business, Trade and Commerce',
    'History of trade and commerce in India',
    'Business, profession and employment',
    'Business risk',
    'Classification of business activities',
    'Industry and commerce',
  ),
  chapter(
    'Forms of Business Organisation',
    'Sole proprietorship',
    'Joint Hindu family business',
    'Partnership',
    'Cooperative societies',
    'Joint stock company',
    'Choice of form of business organisation',
  ),
  chapter(
    'Private, Public and Global Enterprises',
    'Private sector and public sector',
    'Forms of public sector enterprises',
    'Changing role of the public sector',
    'Global enterprises',
    'Joint ventures',
  ),
  chapter(
    'Business Services',
    'Nature of services',
    'Types of services',
    'Banking',
    'Insurance',
    'Communication services',
    'Transportation and warehousing',
  ),
  chapter(
    'Emerging Modes of Business',
    'E-business',
    'Scope and benefits of e-business',
    'Online transactions',
    'Security and safety of e-transactions',
    'Business process outsourcing',
  ),
  chapter(
    'Social Responsibilities of Business and Business Ethics',
    'Concept of social responsibility',
    'Case for social responsibility',
    'Kinds of social responsibility',
    'Business and environmental protection',
    'Business ethics',
  ),
  chapter(
    'Formation of a Company',
    'Promotion of a company',
    'Incorporation',
    'Capital subscription',
    'Documents required',
  ),
  chapter(
    'Sources of Business Finance',
    'Nature and significance of business finance',
    'Classification of sources of funds',
    'Owners funds and borrowed funds',
    'International sources of finance',
  ),
  chapter(
    'Small Business and Entrepreneurship Development',
    'Entrepreneurship development',
    'Small scale enterprises',
    'Role of small business in India',
    'Government schemes and agencies',
  ),
  chapter(
    'Internal Trade',
    'Services of a wholesaler and a retailer',
    'Types of retail trade',
    'Chain stores and mail order houses',
    'Role of the Chambers of Commerce and Industry',
  ),
  chapter(
    'International Business',
    'Scope and benefits of international business',
    'Modes of entry',
    'Export and import procedures',
    'Foreign trade promotion',
    'World Trade Organization',
  ),
);

export const class11Economics = subject(
  'Economics',
  chapter(
    'Statistics: Introduction',
    'What is economics?',
    'Statistics in economics',
    'What is statistics?',
  ),
  chapter(
    'Statistics: Collection of Data',
    'Sources of data',
    'How basic data is collected',
    'Sampling and non-sampling errors',
    'Census and sample surveys',
  ),
  chapter(
    'Statistics: Organisation of Data',
    'Raw data',
    'Classification of data',
    'Variables',
    'Frequency distribution',
  ),
  chapter(
    'Statistics: Presentation of Data',
    'Textual presentation',
    'Tabular presentation',
    'Diagrammatic presentation',
    'Frequency diagrams',
  ),
  chapter(
    'Statistics: Measures of Central Tendency',
    'Arithmetic mean',
    'Median',
    'Mode',
    'Relative position of mean, median and mode',
  ),
  chapter(
    'Statistics: Measures of Dispersion',
    'Range and quartile deviation',
    'Mean deviation',
    'Standard deviation',
    'Lorenz curve',
  ),
  chapter(
    'Statistics: Correlation',
    'Types of correlation',
    'Scatter diagram',
    "Karl Pearson's coefficient of correlation",
    "Spearman's rank correlation",
  ),
  chapter(
    'Statistics: Index Numbers',
    'What is an index number?',
    'Construction of an index number',
    'Consumer price index',
    'Wholesale price index',
    'Index of industrial production',
  ),
  chapter(
    'Indian Economy on the Eve of Independence',
    'Low level of economic development',
    'Agricultural sector',
    'Industrial sector',
    'Foreign trade',
    'Demographic condition',
    'Occupational structure',
  ),
  chapter(
    'Indian Economy 1950-1990',
    'The goals of five year plans',
    'Agriculture',
    'Industry and trade',
    'Trade policy: import substitution',
  ),
  chapter(
    'Liberalisation, Privatisation and Globalisation',
    'Background',
    'Liberalisation',
    'Privatisation',
    'Globalisation',
    'Indian economy during reforms: an assessment',
  ),
  chapter(
    'Human Capital Formation in India',
    'What is human capital?',
    'Sources of human capital',
    'Human capital and economic growth',
    'Education sector in India',
  ),
  chapter(
    'Rural Development',
    'What is rural development?',
    'Credit and marketing in rural areas',
    'Agricultural diversification',
    'Sustainable development and organic farming',
  ),
  chapter(
    'Employment: Growth, Informalisation and Other Issues',
    'Workers and employment',
    'Participation of people in employment',
    'Self-employed and hired workers',
    'Growth and changing structure of employment',
    'Unemployment',
    'Government and employment generation',
  ),
  chapter(
    'Environment and Sustainable Development',
    'Environment: definition and functions',
    'State of India’s environment',
    'Sustainable development',
    'Strategies for sustainable development',
  ),
);

// ---------------------------------------------------------------------------
// Commerce — class 12
// ---------------------------------------------------------------------------

export const class12Accountancy = subject(
  'Accountancy',
  chapter(
    'Accounting for Partnership: Basic Concepts',
    'Nature of partnership',
    'Partnership deed',
    'Provisions of the Partnership Act',
    'Distribution of profit among partners',
    "Partner's capital accounts",
    'Past adjustments',
    'Guarantee of profit to a partner',
  ),
  chapter(
    'Reconstitution of a Partnership Firm — Admission of a Partner',
    'Modes of reconstitution',
    'Admission of a new partner',
    'New profit sharing ratio and sacrificing ratio',
    'Goodwill',
    'Revaluation of assets and reassessment of liabilities',
    'Adjustment of capitals',
  ),
  chapter(
    'Reconstitution — Retirement and Death of a Partner',
    'Ascertaining the amount due to a retiring partner',
    'New profit sharing ratio and gaining ratio',
    'Treatment of goodwill',
    'Adjustment for revaluation',
    'Disposal of the amount due',
    'Death of a partner',
  ),
  chapter(
    'Dissolution of Partnership Firm',
    'Dissolution of partnership and of a firm',
    'Settlement of accounts',
    'Accounting treatment',
    'Realisation account',
  ),
  chapter(
    'Accounting for Share Capital',
    'Features of a company',
    'Kinds of companies',
    'Share capital of a company',
    'Accounting for share capital',
    'Issue of shares at par and premium',
    'Calls in arrears and calls in advance',
    'Forfeiture of shares',
  ),
  chapter(
    'Issue and Redemption of Debentures',
    'Meaning of a debenture',
    'Distinction between shares and debentures',
    'Issue of debentures',
    'Interest on debentures',
    'Writing off discount and loss on issue',
    'Redemption of debentures',
  ),
  chapter(
    'Financial Statements of a Company',
    'Meaning of financial statements',
    'Nature and objectives',
    'Balance sheet as per Schedule III',
    'Statement of profit and loss',
  ),
  chapter(
    'Analysis of Financial Statements',
    'Meaning and significance of analysis',
    'Tools of analysis',
    'Comparative statements',
    'Common size statements',
  ),
  chapter(
    'Accounting Ratios',
    'Objectives and classification of ratios',
    'Liquidity ratios',
    'Solvency ratios',
    'Activity ratios',
    'Profitability ratios',
  ),
  chapter(
    'Cash Flow Statement',
    'Objectives of a cash flow statement',
    'Benefits',
    'Cash and cash equivalents',
    'Classification of activities',
    'Preparation of a cash flow statement',
  ),
);

export const class12BusinessStudies = subject(
  'Business Studies',
  chapter(
    'Nature and Significance of Management',
    'Management: concept, objectives and importance',
    'Nature of management',
    'Levels of management',
    'Functions of management',
    'Coordination as the essence of management',
  ),
  chapter(
    'Principles of Management',
    'Meaning and nature of management principles',
    "Fayol's principles of management",
    'Taylor’s scientific management',
    'Techniques of scientific management',
  ),
  chapter(
    'Business Environment',
    'Concept and importance',
    'Dimensions of business environment',
    'Impact of government policy changes on business',
  ),
  chapter(
    'Planning',
    'Meaning, features and importance of planning',
    'Limitations of planning',
    'Planning process',
    'Types of plans',
  ),
  chapter(
    'Organising',
    'Meaning and importance',
    'Organising process',
    'Organisation structure',
    'Formal and informal organisation',
    'Delegation',
    'Decentralisation',
  ),
  chapter(
    'Staffing',
    'Meaning, need and importance',
    'Staffing as a part of human resource management',
    'Staffing process',
    'Recruitment and selection',
    'Training and development',
  ),
  chapter(
    'Directing',
    'Meaning, features and importance',
    'Elements of directing',
    'Supervision',
    'Motivation',
    'Leadership',
    'Communication',
  ),
  chapter(
    'Controlling',
    'Meaning and importance',
    'Relationship between planning and controlling',
    'Controlling process',
  ),
  chapter(
    'Financial Management',
    'Meaning, role and objectives',
    'Financial decisions',
    'Financial planning',
    'Capital structure',
    'Fixed and working capital',
  ),
  chapter(
    'Financial Markets',
    'Concept and functions of financial markets',
    'Money market and its instruments',
    'Capital market',
    'Stock exchange',
    'Securities and Exchange Board of India',
  ),
  chapter(
    'Marketing',
    'Concept of marketing',
    'Marketing management philosophies',
    'Functions of marketing',
    'Marketing mix',
    'Product, price, place and promotion',
  ),
  chapter(
    'Consumer Protection',
    'Importance of consumer protection',
    'Consumer Protection Act',
    'Consumer rights and responsibilities',
    'Ways and means of consumer protection',
    'Redressal machinery',
  ),
);

export const class12Economics = subject(
  'Economics',
  chapter(
    'Macroeconomics: Introduction',
    'What is macroeconomics?',
    'Emergence of macroeconomics',
    'Context of the present book',
  ),
  chapter(
    'Macroeconomics: National Income Accounting',
    'Some basic concepts',
    'Circular flow of income',
    'Methods of calculating national income',
    'Factor cost, basic prices and market prices',
    'Some macroeconomic identities',
    'Goods and Services Tax',
    'Nominal and real GDP',
    'GDP and welfare',
  ),
  chapter(
    'Macroeconomics: Money and Banking',
    'Functions of money',
    'Demand for money',
    'Supply of money',
    'Money creation by the banking system',
    'Policy tools to control money supply',
  ),
  chapter(
    'Macroeconomics: Determination of Income and Employment',
    'Aggregate demand and its components',
    'Determination of income in the short run',
    'Investment multiplier',
    'Problems of excess and deficient demand',
    'Measures to correct them',
  ),
  chapter(
    'Macroeconomics: Government Budget and the Economy',
    'Components of the government budget',
    'Objectives of the government budget',
    'Classification of receipts and expenditure',
    'Measures of government deficit',
    'Fiscal policy',
  ),
  chapter(
    'Macroeconomics: Open Economy Macroeconomics',
    'Balance of payments',
    'Foreign exchange market',
    'Determination of the exchange rate',
    'Fixed and flexible exchange rates',
    'Managed floating',
  ),
  chapter(
    'Indian Economic Development: Development Experience 1947-90 and Economic Reforms',
    'Economy on the eve of independence',
    'Five year plans',
    'Economic reforms since 1991',
    'Assessment of the reforms',
  ),
  chapter(
    'Indian Economic Development: Current Challenges',
    'Poverty',
    'Rural development',
    'Human capital formation',
    'Employment',
    'Infrastructure',
    'Sustainable economic development',
  ),
  chapter(
    'Indian Economic Development: Development Experience of India — A Comparison with Neighbours',
    'Developmental path: a snapshot view',
    'Demographic indicators',
    'Growth and sectoral indicators',
    'Human development indicators',
    'Appraisal',
  ),
);

// ---------------------------------------------------------------------------
// Humanities — class 11
// ---------------------------------------------------------------------------

export const class11History = subject(
  'History',
  chapter(
    'From the Beginning of Time',
    'Early humans and their evolution',
    'From trees to the ground',
    'Modern human beings',
    'Early societies: hunter-gatherers',
  ),
  chapter(
    'Writing and City Life',
    'Mesopotamia and its geography',
    'The development of writing',
    'Urbanisation in southern Mesopotamia',
    'Life in the city',
    'Legacy of writing',
  ),
  chapter(
    'An Empire Across Three Continents',
    'The Roman Empire',
    'The early empire',
    'The third-century crisis',
    'Gender, literacy and culture',
    'Economic expansion',
    'Late antiquity',
  ),
  chapter(
    'The Central Islamic Lands',
    'The rise of Islam',
    'The caliphate',
    'Crusades',
    'Economy: agriculture and urbanisation',
    'Learning and culture',
  ),
  chapter(
    'Nomadic Empires',
    'Social and political background of the Mongols',
    'Ceremonies of Genghis Khan',
    'The Mongols after Genghis Khan',
    'Situating Genghis Khan in world history',
  ),
  chapter(
    'The Three Orders',
    'The first order: the clergy',
    'The second order: the nobility',
    'The third order: peasants',
    'Factors affecting economy',
    'The fourteenth-century crisis',
  ),
  chapter(
    'Changing Cultural Traditions',
    'The Renaissance',
    'Humanism and the arts',
    'Science and philosophy',
    'The Reformation',
    'Copernican revolution',
  ),
  chapter(
    'Displacing Indigenous Peoples',
    'European imperialism',
    'North America',
    'Australia',
    'Displacement and its consequences',
  ),
  chapter(
    'Paths to Modernisation',
    'Introduction to modern Japan and China',
    'The Meiji restoration',
    'Modernisation of the economy',
    'The Chinese revolution',
    'Establishing the republic',
  ),
);

export const class11PoliticalScience = subject(
  'Political Science',
  chapter(
    'Indian Constitution: Why and How',
    'Why do we need a constitution?',
    'The making of the Indian Constitution',
    'Institutional arrangements',
    'Constitution as a means of democratic transformation',
  ),
  chapter(
    'Rights in the Indian Constitution',
    'The importance of rights',
    'Fundamental rights in the Indian Constitution',
    'Directive principles of state policy',
    'Relationship between fundamental rights and directive principles',
  ),
  chapter(
    'Election and Representation',
    'Elections and democracy',
    'Election system in India',
    'Reservation of constituencies',
    'Free and fair elections',
    'Election Commission',
  ),
  chapter(
    'Executive',
    'What is an executive?',
    'Parliamentary executive in India',
    'Prime minister and the council of ministers',
    'Permanent executive: bureaucracy',
  ),
  chapter(
    'Legislature',
    'Why do we need a parliament?',
    'Two houses of parliament',
    'Functions and powers of the parliament',
    'Parliamentary committees',
    'Self-regulation',
  ),
  chapter(
    'Judiciary',
    'Independence of the judiciary',
    'Structure of the judiciary',
    'Judicial activism',
    'Judiciary and rights',
    'Judiciary and parliament',
  ),
  chapter(
    'Federalism',
    'What is federalism?',
    'Federalism in the Indian Constitution',
    'Division of powers',
    'Conflicts in India’s federal system',
    'Special provisions',
  ),
  chapter(
    'Local Governments',
    'Why local governments?',
    'Growth of local government in India',
    '73rd and 74th amendments',
    'Implementation of the amendments',
  ),
  chapter(
    'Constitution as a Living Document',
    'Are constitutions static?',
    'How to amend the constitution',
    'Contents of amendments',
    'Basic structure doctrine',
  ),
  chapter(
    'The Philosophy of the Constitution',
    'What is meant by philosophy of the constitution?',
    'Political philosophy underlying the constitution',
    'Procedural achievements',
    'Criticisms and limitations',
  ),
  chapter(
    'Political Theory: An Introduction',
    'What is politics?',
    'What do we study in political theory?',
    'Putting political theory to practice',
  ),
  chapter(
    'Freedom',
    'The ideal of freedom',
    'What is freedom?',
    'Sources of constraints',
    'The harm principle',
    'Negative and positive liberty',
  ),
  chapter(
    'Equality',
    'Significance of equality',
    'What is equality?',
    'Different kinds of equality',
    'How can we promote equality?',
  ),
  chapter(
    'Social Justice',
    'What is justice?',
    'Just distribution',
    "John Rawls' theory of justice",
    'Pursuing social justice',
  ),
  chapter(
    'Rights',
    'What are rights?',
    'Where do rights come from?',
    'Legal rights and the state',
    'Kinds of rights',
    'Rights and responsibilities',
  ),
  chapter(
    'Citizenship',
    'What is citizenship?',
    'Full and equal membership',
    'Equal rights',
    'Universal citizenship',
    'Global citizenship',
  ),
  chapter(
    'Nationalism',
    'Introducing nationalism',
    'Nations and nationalism',
    'National self-determination',
    'Nationalism and pluralism',
  ),
  chapter(
    'Secularism',
    'What is secularism?',
    'Inter-religious and intra-religious domination',
    'The western and Indian models of secularism',
    'Criticisms of Indian secularism',
  ),
);

export const class11Geography = subject(
  'Geography',
  chapter(
    'Geography as a Discipline',
    'Geography as an integrating discipline',
    'Branches of geography',
    'Physical geography and natural sciences',
  ),
  chapter(
    'The Origin and Evolution of the Earth',
    'Origin of the earth',
    'The star formation and the big bang theory',
    'Evolution of the lithosphere',
    'Evolution of the atmosphere and hydrosphere',
  ),
  chapter(
    'Interior of the Earth',
    'Sources of information about the interior',
    'Earthquakes',
    'Structure of the earth',
    'Volcanoes and volcanic landforms',
  ),
  chapter(
    'Geomorphic Processes',
    'Endogenic and exogenic processes',
    'Weathering',
    'Mass movements',
    'Erosion and deposition',
  ),
  chapter(
    'Landforms and their Evolution',
    'Running water',
    'Groundwater',
    'Glaciers',
    'Waves and currents',
    'Winds',
  ),
  chapter(
    'Composition and Structure of Atmosphere',
    'Composition of the atmosphere',
    'Structure of the atmosphere',
    'Elements of weather and climate',
  ),
  chapter(
    'Solar Radiation, Heat Balance and Temperature',
    'Solar radiation',
    'Heating and cooling of the atmosphere',
    'Heat budget of the planet earth',
    'Distribution of temperature',
    'Inversion of temperature',
  ),
  chapter(
    'Atmospheric Circulation and Weather Systems',
    'Atmospheric pressure',
    'Wind',
    'General circulation of the atmosphere',
    'Air masses and fronts',
    'Extra-tropical and tropical cyclones',
  ),
  chapter(
    'Water in the Atmosphere',
    'Evaporation and condensation',
    'Humidity',
    'Clouds',
    'Types of precipitation',
    'World distribution of rainfall',
  ),
  chapter(
    'World Climate and Climate Change',
    'World climates',
    'Koeppen’s scheme of classification',
    'Climate change',
    'Global warming',
  ),
  chapter(
    'Water (Oceans)',
    'Hydrological cycle',
    'Relief of the ocean floor',
    'Temperature and salinity of ocean waters',
  ),
  chapter('Movements of Ocean Water', 'Waves', 'Tides', 'Ocean currents'),
  chapter(
    'Biodiversity and Conservation',
    'Biodiversity',
    'Loss of biodiversity',
    'Conservation of biodiversity',
  ),
  chapter(
    'India: Location, Structure and Physiography',
    'India — location and space relations',
    'Structure and relief',
    'Physiographic divisions',
  ),
  chapter(
    'India: Drainage System',
    'Drainage systems of India',
    'The Himalayan drainage',
    'The Peninsular drainage',
  ),
  chapter(
    'India: Climate, Vegetation and Soils',
    'Unity and diversity in the monsoon climate',
    'Climatic regions of India',
    'Natural vegetation',
    'Types of soils and soil degradation',
  ),
  chapter(
    'India: Natural Hazards and Disasters',
    'Earthquakes and tsunami',
    'Tropical cyclones',
    'Floods and droughts',
    'Landslides',
    'Disaster management',
  ),
);

export const class11Psychology = subject(
  'Psychology',
  chapter(
    'What is Psychology?',
    'What is psychology?',
    'Understanding mind and behaviour',
    'Psychology as a discipline and a natural and social science',
    'Development of psychology',
    'Branches of psychology',
    'Psychology in everyday life',
  ),
  chapter(
    'Methods of Enquiry in Psychology',
    'Goals of psychological enquiry',
    'Nature of psychological data',
    'Some important methods',
    'Observational method',
    'Experimental method',
    'Correlational research',
    'Analysis of data',
    'Ethical issues',
  ),
  chapter(
    'The Bases of Human Behaviour',
    'Evolutionary perspective',
    'Biological and cultural roots',
    'Structure and functions of the nervous system',
    'The endocrine system',
    'Heredity: genes and behaviour',
    'Cultural transmission and socialisation',
  ),
  chapter(
    'Human Development',
    'Meaning of development',
    'Factors influencing development',
    'Context of development',
    'Overview of developmental stages',
  ),
  chapter(
    'Sensory, Attentional and Perceptual Processes',
    'Knowing the world',
    'Nature and varieties of stimulus',
    'Functional limitations of sense organs',
    'Attentional processes',
    'Perceptual processes',
    'Perception of space, depth and distance',
    'Perceptual constancies and illusions',
  ),
  chapter(
    'Learning',
    'Nature of learning',
    'Paradigms of learning',
    'Classical conditioning',
    'Operant conditioning',
    'Observational and cognitive learning',
    'Verbal learning',
    'Transfer of learning',
    'Learning disabilities',
  ),
  chapter(
    'Human Memory',
    'Nature of memory',
    'Information processing approach',
    'Memory systems',
    'Levels of processing',
    'Types of long-term memory',
    'Nature and causes of forgetting',
    'Enhancing memory',
  ),
  chapter(
    'Thinking',
    'Nature of thinking',
    'The building blocks of thought',
    'Problem solving',
    'Reasoning and decision making',
    'Nature of creative thinking',
    'Thought and language',
    'Development of language and language use',
  ),
  chapter(
    'Motivation and Emotion',
    'Nature of motivation',
    'Types of motives',
    "Maslow's hierarchy of needs",
    'Nature of emotions',
    'Physiological and cognitive bases of emotions',
    'Expression of emotions',
    'Managing negative emotions',
  ),
);

export const class11Sociology = subject(
  'Sociology',
  chapter(
    'Sociology and Society',
    'Understanding sociology',
    'The intellectual ideas and material issues',
    'The growth of sociology in India',
    'The scope of sociology and its relationship to other disciplines',
  ),
  chapter(
    'Terms, Concepts and their Use in Sociology',
    'Social groups and society',
    'Status and role',
    'Social stratification',
    'Social control',
  ),
  chapter(
    'Understanding Social Institutions',
    'Family, marriage and kinship',
    'Work and economic life',
    'Political institutions',
    'Religion as a social institution',
    'Education as a social institution',
  ),
  chapter(
    'Culture and Socialisation',
    'Defining culture',
    'Dimensions of culture',
    'Cultural change',
    'Socialisation',
    'Agencies of socialisation',
  ),
  chapter(
    'Doing Sociology: Research Methods',
    'The relationship between cause and effect',
    'Objectivity and subjectivity in sociology',
    'Participant observation',
    'Surveys',
    'Interviews',
  ),
  chapter(
    'Social Structure, Stratification and Social Processes in Society',
    'Visions of social structure',
    'The relationship between the individual and society',
    'Cooperation, competition and conflict',
  ),
  chapter(
    'Social Change and Social Order in Rural and Urban Society',
    'Social change',
    'Types of social change',
    'Social order',
    'Village and town in Indian society',
  ),
  chapter(
    'Environment and Society',
    'Ecology and society',
    'Environmental problems and social inequality',
    'Sociology of environment',
    'Common property resources',
  ),
  chapter(
    'Introducing Western Sociologists',
    'Karl Marx on class conflict',
    'Emile Durkheim on division of labour',
    'Max Weber and interpretive sociology',
  ),
  chapter(
    'Indian Sociologists',
    'G. S. Ghurye on caste and race',
    'D. P. Mukerji on tradition and change',
    'A. R. Desai on the state',
    'M. N. Srinivas on the village',
  ),
);

// ---------------------------------------------------------------------------
// Humanities — class 12
// ---------------------------------------------------------------------------

export const class12History = subject(
  'History',
  chapter(
    'Bricks, Beads and Bones: The Harappan Civilisation',
    'The story of the first discoveries',
    'Subsistence strategies',
    'Mohenjodaro: a planned urban centre',
    'Tracking social differences',
    'Strategies for procuring materials',
    'Seals, script and weights',
    'The end of the civilisation',
  ),
  chapter(
    'Kings, Farmers and Towns: Early States and Economies',
    'Prinsep and Piyadassi',
    'The earliest states',
    'An early empire',
    'New notions of kingship',
    'Towards habitation to empire',
    'A changing countryside',
    'Urban centres and trade',
    'Back to basics: how are inscriptions deciphered?',
  ),
  chapter(
    'Kinship, Caste and Class: Early Societies',
    'The critical edition of the Mahabharata',
    'Kinship and marriage',
    'Social differences: within and beyond the framework of caste',
    'Beyond birth: resources and status',
    'Explaining social differences',
  ),
  chapter(
    'Thinkers, Beliefs and Buildings: Cultural Developments',
    'A glimpse of Sanchi',
    'The background: sacrificial traditions',
    'New questions and new ideas',
    'The Buddha and the quest for enlightenment',
    'Stupas',
    'Sculpture and the developments in religious traditions',
  ),
  chapter(
    'Through the Eyes of Travellers: Perceptions of Society',
    'Al-Biruni and the Kitab-ul-Hind',
    "Ibn Battuta's Rihla",
    'Francois Bernier and the "degenerate" east',
    'Women: slaves, sati and workers',
  ),
  chapter(
    'Bhakti-Sufi Traditions: Changes in Religious Beliefs',
    'A mosaic of religious beliefs and practices',
    'Poems of prayer: early traditions of bhakti',
    'The growth of Sufism',
    'New devotional paths',
    'Reconstructing histories of religious traditions',
  ),
  chapter(
    'An Imperial Capital: Vijayanagara',
    'The discovery of Hampi',
    'Rayas, nayakas and sultans',
    'Vijayanagara: the capital and its environs',
    'The royal centre',
    'Questions of interpretation',
  ),
  chapter(
    'Peasants, Zamindars and the State: Agrarian Society',
    'Peasants and agricultural production',
    'The village community',
    'Women in agrarian society',
    'Forests and tribes',
    'The zamindars',
    'Land revenue system',
    'The Ain-i Akbari of Abu’l Fazl',
  ),
  chapter(
    'Colonialism and the Countryside',
    'Bengal and the zamindars',
    'The hoe and the plough',
    'A revolt in the countryside: the Bombay Deccan',
    'Official reports as a source of information',
  ),
  chapter(
    'Rebels and the Raj: The Revolt of 1857',
    'Pattern of the rebellion',
    'Awadh in revolt',
    'What the rebels wanted',
    'Repression',
    'Images of the revolt',
  ),
  chapter(
    'Mahatma Gandhi and the Nationalist Movement',
    'A leader announces himself',
    'The making and unmaking of non-cooperation',
    'The salt satyagraha',
    'Quit India',
    'The last heroic days',
    'Knowing Gandhi through different sources',
  ),
  chapter(
    'Framing the Constitution: The Beginning of a New Era',
    'A tumultuous time',
    'The vision of the constitution',
    'Defining rights',
    'The powers of the state',
    'The language of the nation',
  ),
);

export const class12PoliticalScience = subject(
  'Political Science',
  chapter(
    'The Cold War Era',
    'What is the Cold War?',
    'The emergence of two power blocs',
    'Challenge to bipolarity',
    'India and the Cold War',
  ),
  chapter(
    'The End of Bipolarity',
    'The Soviet system',
    'Gorbachev and the disintegration',
    'Consequences of disintegration',
    'Shock therapy in post-communist regimes',
    'India and post-communist countries',
  ),
  chapter(
    'US Hegemony in World Politics',
    'The beginning of the new world order',
    'The Gulf War',
    'The 9/11 attacks',
    'The nature of hegemony',
    'Constraints on American power',
    'India’s relationship with the US',
  ),
  chapter(
    'Alternative Centres of Power',
    'European Union',
    'Association of South East Asian Nations',
    'The rise of the Chinese economy',
    'India-China relations',
  ),
  chapter(
    'Contemporary South Asia',
    'What is South Asia?',
    'Military and democracy in Pakistan and Bangladesh',
    'Monarchy and democracy in Nepal',
    'Ethnic conflict in Sri Lanka',
    'India-Pakistan conflicts',
    'Peace and cooperation',
  ),
  chapter(
    'International Organisations',
    'Why international organisations?',
    'Evolution of the UN',
    'Reform of the UN after the Cold War',
    'India and the UN',
    'The IMF, World Bank and WTO',
  ),
  chapter(
    'Security in the Contemporary World',
    'What is security?',
    'Traditional notions of security',
    'Non-traditional notions of security',
    'Cooperative security',
    'India’s security strategy',
  ),
  chapter(
    'Environment and Natural Resources',
    'Environmental concerns in global politics',
    'The Earth Summit',
    'Global commons',
    'Common but differentiated responsibilities',
    'India’s stand',
    'Resource geopolitics',
    'The indigenous people',
  ),
  chapter(
    'Globalisation',
    'Concept of globalisation',
    'Causes of globalisation',
    'Political, economic and cultural consequences',
    'India and globalisation',
    'Resistance to globalisation',
  ),
  chapter(
    'Challenges of Nation Building',
    'Three challenges',
    'Partition: displacement and rehabilitation',
    'Integration of princely states',
    'Reorganisation of states',
  ),
  chapter(
    'Era of One-Party Dominance',
    'Challenge of building democracy',
    'Congress dominance in the first three general elections',
    'Nature of Congress dominance',
    'Emergence of the opposition parties',
  ),
  chapter(
    'Politics of Planned Development',
    'Political contestation',
    'Ideas of development',
    'Planning Commission and five year plans',
    'Key controversies',
    'Major outcomes',
  ),
  chapter(
    'India’s External Relations',
    'International context',
    'The policy of non-alignment',
    'Peace and conflict with China and Pakistan',
    'India’s nuclear policy',
    'Shifting alliances in world politics',
  ),
  chapter(
    'Challenges to and Restoration of the Congress System',
    'Challenge of political succession',
    'Fourth general elections and the context of 1967',
    'Split in the Congress',
    'The 1971 election and the restoration of the Congress',
  ),
  chapter(
    'The Crisis of Democratic Order',
    'Background to the emergency',
    'The declaration of the emergency',
    'Consequences',
    'Lessons of the emergency',
    'Politics after the emergency',
  ),
  chapter(
    'Regional Aspirations',
    'Region and nation',
    'Jammu and Kashmir',
    'Punjab',
    'The North-East',
    'Accommodation and national integration',
  ),
  chapter(
    'Recent Developments in Indian Politics',
    'Context of the 1990s',
    'Era of coalitions',
    'Political rise of the backward classes',
    'Communalism and the Ayodhya dispute',
    'Emerging consensus',
  ),
);

export const class12Geography = subject(
  'Geography',
  chapter(
    'Human Geography: Nature and Scope',
    'Nature of human geography',
    'Human geography through the corridors of time',
    'Fields and sub-fields of human geography',
  ),
  chapter(
    'The World Population: Distribution, Density and Growth',
    'Patterns of population distribution',
    'Density of population',
    'Factors influencing distribution',
    'Population growth',
    'Demographic transition',
    'Population control measures',
  ),
  chapter(
    'Population Composition',
    'Sex composition',
    'Age structure and the age-sex pyramid',
    'Rural-urban composition',
    'Literacy',
    'Occupational structure',
  ),
  chapter(
    'Human Development',
    'Growth and development',
    'The four pillars of human development',
    'Approaches to human development',
    'Measuring human development',
  ),
  chapter('Primary Activities', 'Hunting and gathering', 'Pastoralism', 'Agriculture', 'Mining'),
  chapter(
    'Secondary Activities',
    'Manufacturing',
    'Classification of manufacturing industries',
    'Concept of high technology industry',
  ),
  chapter(
    'Tertiary and Quaternary Activities',
    'Types of tertiary activities',
    'Trade and commerce',
    'Transport, communication and services',
    'Quaternary and quinary activities',
  ),
  chapter(
    'Transport and Communication',
    'Land, water and air transport',
    'Oil and gas pipelines',
    'Satellite communication and cyber space',
  ),
  chapter(
    'International Trade',
    'History of international trade',
    'Basis of international trade',
    'Aspects of international trade',
    'World Trade Organization',
    'Ports as gateways of international trade',
  ),
  chapter(
    'Human Settlements',
    'Classification of settlements',
    'Rural settlements',
    'Urban settlements',
    'Problems of human settlements in developing countries',
  ),
  chapter(
    'India: Population — Distribution, Density, Growth and Composition',
    'Distribution of population in India',
    'Density of population',
    'Growth of population',
    'Population composition',
  ),
  chapter(
    'India: Migration and Human Settlements',
    'Streams of migration',
    'Causes and consequences of migration',
    'Rural and urban settlements in India',
  ),
  chapter(
    'India: Land Resources and Agriculture',
    'Land use categories',
    'Cropping seasons and types of farming',
    'Foodgrains and other crops',
    'Agricultural development and problems',
  ),
  chapter(
    'India: Water and Mineral Resources',
    'Water resources of India',
    'Water demand and utilisation',
    'Deterioration of water quality',
    'Types of mineral resources',
    'Conventional and non-conventional energy sources',
  ),
  chapter(
    'India: Manufacturing Industries and Planning',
    'Types of industries',
    'Location of industries',
    'Agro-based and mineral-based industries',
    'Planning in India',
    'Sustainable development',
  ),
  chapter(
    'India: Transport, Communication and International Trade',
    'Land, water and air transport in India',
    'Communication networks',
    'India’s international trade',
    'Changing pattern of composition of exports and imports',
  ),
  chapter(
    'India: Geographical Perspective on Selected Issues and Problems',
    'Environmental pollution',
    'Urban waste disposal',
    'Rural-urban migration',
    'Land degradation',
  ),
);

export const class12Psychology = subject(
  'Psychology',
  chapter(
    'Variations in Psychological Attributes',
    'Individual differences in human functioning',
    'Assessment of psychological attributes',
    'Intelligence',
    'Theories of intelligence',
    'Individual differences in intelligence',
    'Culture and intelligence',
    'Special abilities',
    'Creativity',
  ),
  chapter(
    'Self and Personality',
    'Self and personality',
    'Concept of self',
    'Cognitive and behavioural aspects of self',
    'Culture and self',
    'Concept of personality',
    'Major approaches to personality',
    'Assessment of personality',
  ),
  chapter(
    'Meeting Life Challenges',
    'Nature, types and sources of stress',
    'Effects of stress on psychological functioning and health',
    'Coping with stress',
    'Promoting positive health and well-being',
  ),
  chapter(
    'Psychological Disorders',
    'Concepts of abnormality and psychological disorders',
    'Classification of psychological disorders',
    'Factors underlying abnormal behaviour',
    'Major psychological disorders',
  ),
  chapter(
    'Therapeutic Approaches',
    'Nature and process of psychotherapy',
    'Types of therapies',
    'Rehabilitation of the mentally ill',
  ),
  chapter(
    'Attitude and Social Cognition',
    'Explaining social behaviour',
    'Nature and components of attitudes',
    'Attitude formation and change',
    'Prejudice and discrimination',
    'Social cognition',
    'Pro-social behaviour',
  ),
  chapter(
    'Social Influence and Group Processes',
    'Nature and formation of groups',
    'Type of groups',
    'Social influence',
    'Conformity, compliance and obedience',
    'Cooperation and competition',
    'Social identity',
    'Intergroup conflict',
  ),
);

export const class12Sociology = subject(
  'Sociology',
  chapter(
    'Introducing Indian Society',
    'Colonialism, nationalism and the emergence of Indian society',
    'Understanding our own society',
  ),
  chapter(
    'The Demographic Structure of Indian Society',
    'Introduction to demography',
    'Some theories and concepts',
    'Common concepts and indicators',
    'The size and growth of India’s population',
    'Age structure and the sex ratio',
    'Literacy and rural-urban distribution',
  ),
  chapter(
    'Social Institutions: Continuity and Change',
    'Caste and the caste system',
    'Tribal communities',
    'The family and kinship',
  ),
  chapter(
    'The Market as a Social Institution',
    'Sociological perspectives on markets and the economy',
    'Understanding capitalism as a social system',
    'Markets in Indian history',
    'Globalisation and liberalisation',
  ),
  chapter(
    'Patterns of Social Inequality and Exclusion',
    'Social inequality and exclusion',
    'Systems justifying and perpetuating inequality',
    'Caste and tribe',
    'The struggle for women’s equality',
    'The struggles of the differently abled',
  ),
  chapter(
    'The Challenges of Cultural Diversity',
    'Cultural communities and the nation state',
    'Community identity and the nation state',
    'Regionalism',
    'Minority rights and the nation',
    'Communalism, secularism and the nation state',
    'State and civil society',
  ),
  chapter(
    'Structural Change',
    'Colonialism and its consequences',
    'Industrialisation and urbanisation',
  ),
  chapter(
    'Cultural Change',
    'Social reform movements',
    'Sanskritisation, modernisation, secularisation and westernisation',
  ),
  chapter(
    'The Story of Indian Democracy',
    'The Indian Constitution as an instrument of social change',
    'Panchayati Raj and the challenges of social transformation',
    'Political parties, pressure groups and democratic politics',
  ),
  chapter(
    'Change and Development in Rural Society',
    'Structural change and agrarian society',
    'Land reforms',
    'The Green Revolution and its social consequences',
    'Transformations in rural society',
    'Circulation of labour',
  ),
  chapter(
    'Change and Development in Industrial Society',
    'Industrialisation in India',
    'How people find jobs',
    'How is work carried out?',
    'Working conditions and strikes',
  ),
  chapter(
    'Globalisation and Social Change',
    'The interlinking of the world',
    'Globalisation in India',
    'Political, economic and cultural changes',
    'Globalisation and its critics',
  ),
  chapter(
    'Mass Media and Communications',
    'Modern mass media',
    'Mass media in independent India',
    'Globalisation and the media',
    'Radio, television and print media today',
  ),
  chapter(
    'Social Movements',
    'Social movements: features and theories',
    'Types of social movements',
    'Ecological, class-based and caste-based movements',
    'Women’s movements',
    'Tribal movements',
  ),
);
