import { chapter, subject } from './builder';

/**
 * The science and mathematics subjects of CBSE classes 11 and 12.
 *
 * Written once and shared by the streams that take them: class 11 Physics is
 * the same syllabus whether a student is in PCM or PCMB, and duplicating it per
 * stream is how the two copies drift apart.
 */

// ---------------------------------------------------------------------------
// Class 11
// ---------------------------------------------------------------------------

export const class11Physics = subject(
  'Physics',
  chapter(
    'Units and Measurements',
    'The international system of units',
    'Measurement of length, mass and time',
    'Accuracy, precision and errors in measurement',
    'Significant figures',
    'Dimensional formulae and dimensional analysis',
  ),
  chapter(
    'Motion in a Straight Line',
    'Instantaneous velocity and speed',
    'Acceleration',
    'Kinematic equations for uniformly accelerated motion',
    'Relative velocity',
  ),
  chapter(
    'Motion in a Plane',
    'Scalars and vectors',
    'Addition and subtraction of vectors',
    'Resolution of vectors',
    'Motion in a plane',
    'Projectile motion',
    'Uniform circular motion',
  ),
  chapter(
    'Laws of Motion',
    'Aristotle’s fallacy and the law of inertia',
    "Newton's first, second and third laws",
    'Conservation of momentum',
    'Equilibrium of a particle',
    'Friction',
    'Circular motion',
  ),
  chapter(
    'Work, Energy and Power',
    'Work done by a constant and a variable force',
    'Kinetic energy and the work-energy theorem',
    'Potential energy',
    'Conservation of mechanical energy',
    'Power',
    'Collisions',
  ),
  chapter(
    'System of Particles and Rotational Motion',
    'Centre of mass',
    'Motion of the centre of mass',
    'Vector product of two vectors',
    'Angular velocity and angular acceleration',
    'Torque and angular momentum',
    'Equilibrium of a rigid body',
    'Moment of inertia',
    'Theorems of perpendicular and parallel axes',
    'Rolling motion',
  ),
  chapter(
    'Gravitation',
    "Kepler's laws",
    'Universal law of gravitation',
    'Acceleration due to gravity',
    'Gravitational potential energy',
    'Escape speed',
    'Earth satellites',
    'Energy of an orbiting satellite',
  ),
  chapter(
    'Mechanical Properties of Solids',
    'Stress and strain',
    "Hooke's law",
    'Stress-strain curve',
    'Elastic moduli',
    'Applications of elastic behaviour',
  ),
  chapter(
    'Mechanical Properties of Fluids',
    'Pressure',
    "Pascal's law",
    'Streamline flow',
    "Bernoulli's principle",
    'Viscosity',
    'Surface tension',
  ),
  chapter(
    'Thermal Properties of Matter',
    'Temperature and heat',
    'Measurement of temperature',
    'Thermal expansion',
    'Specific heat capacity',
    'Calorimetry',
    'Change of state and latent heat',
    'Heat transfer',
    "Newton's law of cooling",
  ),
  chapter(
    'Thermodynamics',
    'Thermal equilibrium and the zeroth law',
    'Heat, internal energy and work',
    'First law of thermodynamics',
    'Thermodynamic state variables and processes',
    'Second law of thermodynamics',
    'Reversible and irreversible processes',
    'Carnot engine',
  ),
  chapter(
    'Kinetic Theory',
    'Molecular nature of matter',
    'Behaviour of gases',
    'Kinetic theory of an ideal gas',
    'Law of equipartition of energy',
    'Specific heat capacity',
    'Mean free path',
  ),
  chapter(
    'Oscillations',
    'Periodic and oscillatory motion',
    'Simple harmonic motion',
    'Velocity and acceleration in SHM',
    'Force law for SHM',
    'Energy in SHM',
    'The simple pendulum',
  ),
  chapter(
    'Waves',
    'Transverse and longitudinal waves',
    'Displacement relation in a progressive wave',
    'The speed of a travelling wave',
    'The principle of superposition',
    'Reflection of waves',
    'Standing waves and normal modes',
    'Beats',
  ),
);

export const class11Chemistry = subject(
  'Chemistry',
  chapter(
    'Some Basic Concepts of Chemistry',
    'Nature of matter',
    'Properties and their measurement',
    'Laws of chemical combination',
    'Dalton’s atomic theory',
    'Atomic and molecular masses',
    'The mole concept and molar mass',
    'Percentage composition',
    'Stoichiometry and stoichiometric calculations',
  ),
  chapter(
    'Structure of Atom',
    'Discovery of subatomic particles',
    'Atomic models',
    'Developments leading to the Bohr model',
    'Bohr’s model for the hydrogen atom',
    'Towards the quantum mechanical model',
    'Quantum mechanical model of the atom',
  ),
  chapter(
    'Classification of Elements and Periodicity in Properties',
    'Genesis of periodic classification',
    'Modern periodic law',
    'Nomenclature of elements with atomic number above 100',
    'Electronic configurations and the periodic table',
    'Electronic configuration and types of elements',
    'Periodic trends in properties of elements',
  ),
  chapter(
    'Chemical Bonding and Molecular Structure',
    'Kössel-Lewis approach to chemical bonding',
    'Ionic or electrovalent bond',
    'Bond parameters',
    'The valence shell electron pair repulsion theory',
    'Valence bond theory',
    'Hybridisation',
    'Molecular orbital theory',
    'Hydrogen bonding',
  ),
  chapter(
    'Thermodynamics',
    'Thermodynamic terms',
    'Applications',
    'Measurement of ΔU and ΔH: calorimetry',
    'Enthalpy change of a reaction',
    'Enthalpies for different types of reactions',
    'Spontaneity',
    'Gibbs energy change and equilibrium',
  ),
  chapter(
    'Equilibrium',
    'Equilibrium in physical processes',
    'Equilibrium in chemical processes',
    'Law of chemical equilibrium and equilibrium constant',
    'Homogeneous and heterogeneous equilibria',
    'Factors affecting equilibria',
    'Ionic equilibrium in solution',
    'Acids, bases and salts',
    'Ionisation of acids and bases',
    'Buffer solutions',
    'Solubility equilibria',
  ),
  chapter(
    'Redox Reactions',
    'Classical idea of redox reactions',
    'Redox reactions in terms of electron transfer',
    'Oxidation number',
    'Redox reactions and electrode processes',
  ),
  chapter(
    'Organic Chemistry — Some Basic Principles and Techniques',
    'General introduction',
    'Tetravalence of carbon and shapes of organic compounds',
    'Structural representations',
    'Classification of organic compounds',
    'Nomenclature',
    'Isomerism',
    'Fundamental concepts in organic reaction mechanism',
    'Methods of purification',
    'Qualitative and quantitative analysis',
  ),
  chapter(
    'Hydrocarbons',
    'Classification',
    'Alkanes',
    'Alkenes',
    'Alkynes',
    'Aromatic hydrocarbons',
    'Carcinogenicity and toxicity',
  ),
);

export const class11Mathematics = subject(
  'Mathematics',
  chapter(
    'Sets',
    'Sets and their representations',
    'Empty, finite and infinite sets',
    'Subsets',
    'Venn diagrams',
    'Operations on sets',
    'Complement of a set',
  ),
  chapter(
    'Relations and Functions',
    'Cartesian product of sets',
    'Relations',
    'Functions',
    'Algebra of real functions',
  ),
  chapter(
    'Trigonometric Functions',
    'Angles and their measurement',
    'Trigonometric functions',
    'Trigonometric functions of the sum and difference of two angles',
    'Trigonometric equations',
  ),
  chapter(
    'Complex Numbers and Quadratic Equations',
    'Complex numbers',
    'Algebra of complex numbers',
    'The modulus and the conjugate',
    'Argand plane and polar representation',
    'Quadratic equations',
  ),
  chapter(
    'Linear Inequalities',
    'Inequalities',
    'Algebraic solutions of linear inequalities in one variable',
    'Graphical solution of linear inequalities in two variables',
  ),
  chapter(
    'Permutations and Combinations',
    'Fundamental principle of counting',
    'Permutations',
    'Combinations',
  ),
  chapter(
    'Binomial Theorem',
    'Binomial theorem for positive integral indices',
    'General and middle terms',
  ),
  chapter(
    'Sequences and Series',
    'Sequences',
    'Series',
    'Arithmetic progression',
    'Geometric progression',
    'Relationship between AM and GM',
  ),
  chapter(
    'Straight Lines',
    'Slope of a line',
    'Various forms of the equation of a line',
    'General equation of a line',
    'Distance of a point from a line',
  ),
  chapter('Conic Sections', 'Sections of a cone', 'Circle', 'Parabola', 'Ellipse', 'Hyperbola'),
  chapter(
    'Introduction to Three Dimensional Geometry',
    'Coordinate axes and coordinate planes',
    'Coordinates of a point in space',
    'Distance between two points',
  ),
  chapter(
    'Limits and Derivatives',
    'Intuitive idea of derivatives',
    'Limits',
    'Limits of trigonometric functions',
    'Derivatives',
    'Algebra of derivative of functions',
  ),
  chapter(
    'Statistics',
    'Measures of dispersion',
    'Range',
    'Mean deviation',
    'Variance and standard deviation',
  ),
  chapter('Probability', 'Random experiments', 'Event', 'Axiomatic approach to probability'),
);

export const class11Biology = subject(
  'Biology',
  chapter(
    'The Living World',
    'What is living?',
    'Diversity in the living world',
    'Taxonomic categories',
  ),
  chapter(
    'Biological Classification',
    'Kingdom Monera',
    'Kingdom Protista',
    'Kingdom Fungi',
    'Kingdom Plantae',
    'Kingdom Animalia',
    'Viruses, viroids, prions and lichens',
  ),
  chapter(
    'Plant Kingdom',
    'Algae',
    'Bryophytes',
    'Pteridophytes',
    'Gymnosperms',
    'Angiosperms',
    'Plant life cycles and alternation of generations',
  ),
  chapter(
    'Animal Kingdom',
    'Basis of classification',
    'Classification of animals',
    'Phylum-level characteristics',
  ),
  chapter(
    'Morphology of Flowering Plants',
    'The root',
    'The stem',
    'The leaf',
    'The inflorescence',
    'The flower',
    'The fruit',
    'The seed',
    'Description of some important families',
  ),
  chapter(
    'Anatomy of Flowering Plants',
    'The tissues',
    'The tissue system',
    'Anatomy of dicotyledonous and monocotyledonous plants',
  ),
  chapter(
    'Structural Organisation in Animals',
    'Animal tissues',
    'Organ and organ system',
    'Morphology and anatomy of the frog',
  ),
  chapter(
    'Cell: The Unit of Life',
    'What is a cell?',
    'Cell theory',
    'An overview of cell',
    'Prokaryotic cells',
    'Eukaryotic cells',
    'Cell organelles',
  ),
  chapter(
    'Biomolecules',
    'How to analyse chemical composition?',
    'Primary and secondary metabolites',
    'Biomacromolecules',
    'Proteins',
    'Polysaccharides',
    'Nucleic acids',
    'Enzymes',
  ),
  chapter(
    'Cell Cycle and Cell Division',
    'Cell cycle',
    'M phase',
    'Significance of mitosis',
    'Meiosis',
    'Significance of meiosis',
  ),
  chapter(
    'Photosynthesis in Higher Plants',
    'What do we know?',
    'Early experiments',
    'Where does photosynthesis take place?',
    'The photosynthetic pigments',
    'Light reaction',
    'The electron transport',
    'The C3 and C4 pathways',
    'Photorespiration',
    'Factors affecting photosynthesis',
  ),
  chapter(
    'Respiration in Plants',
    'Do plants breathe?',
    'Glycolysis',
    'Fermentation',
    'Aerobic respiration',
    'The respiratory balance sheet',
    'Amphibolic pathway',
    'Respiratory quotient',
  ),
  chapter(
    'Plant Growth and Development',
    'Growth',
    'Differentiation, dedifferentiation and redifferentiation',
    'Development',
    'Plant growth regulators',
    'Photoperiodism',
    'Vernalisation',
  ),
  chapter(
    'Breathing and Exchange of Gases',
    'Respiratory organs',
    'Mechanism of breathing',
    'Exchange of gases',
    'Transport of gases',
    'Regulation of respiration',
    'Disorders of the respiratory system',
  ),
  chapter(
    'Body Fluids and Circulation',
    'Blood',
    'Lymph',
    'Circulatory pathways',
    'Double circulation',
    'Regulation of cardiac activity',
    'Disorders of the circulatory system',
  ),
  chapter(
    'Excretory Products and their Elimination',
    'Human excretory system',
    'Urine formation',
    'Function of the tubules',
    'Mechanism of concentration of the filtrate',
    'Regulation of kidney function',
    'Micturition',
    'Disorders of the excretory system',
  ),
  chapter(
    'Locomotion and Movement',
    'Types of movement',
    'Muscle',
    'Skeletal system',
    'Joints',
    'Disorders of the muscular and skeletal system',
  ),
  chapter(
    'Neural Control and Coordination',
    'Neural system',
    'Human neural system',
    'Neuron as a structural and functional unit',
    'Central neural system',
    'Reflex action and reflex arc',
    'Sensory reception and processing',
  ),
  chapter(
    'Chemical Coordination and Integration',
    'Endocrine glands and hormones',
    'Human endocrine system',
    'Hormones of the heart, kidney and gastrointestinal tract',
    'Mechanism of hormone action',
  ),
);

// ---------------------------------------------------------------------------
// Class 12
// ---------------------------------------------------------------------------

export const class12Physics = subject(
  'Physics',
  chapter(
    'Electric Charges and Fields',
    'Electric charge',
    'Conductors and insulators',
    "Coulomb's law",
    'Forces between multiple charges',
    'Electric field',
    'Electric field lines',
    'Electric flux',
    'Electric dipole',
    "Gauss's law and its applications",
  ),
  chapter(
    'Electrostatic Potential and Capacitance',
    'Electrostatic potential',
    'Potential due to a point charge and a dipole',
    'Equipotential surfaces',
    'Potential energy of a system of charges',
    'Electrostatics of conductors',
    'Dielectrics and polarisation',
    'Capacitors and capacitance',
    'Combination of capacitors',
    'Energy stored in a capacitor',
  ),
  chapter(
    'Current Electricity',
    'Electric current',
    'Drift of electrons',
    "Ohm's law",
    'Resistivity of various materials',
    'Temperature dependence of resistivity',
    'Electrical energy and power',
    'Cells, emf and internal resistance',
    'Cells in series and parallel',
    "Kirchhoff's rules",
    'Wheatstone bridge',
  ),
  chapter(
    'Moving Charges and Magnetism',
    'Magnetic force',
    'Motion in a magnetic field',
    'Magnetic field due to a current element: Biot-Savart law',
    "Ampere's circuital law",
    'The solenoid',
    'Force between two parallel currents',
    'Torque on a current loop',
    'The moving coil galvanometer',
  ),
  chapter(
    'Magnetism and Matter',
    'The bar magnet',
    'Magnetism and Gauss’s law',
    'Magnetisation and magnetic intensity',
    'Magnetic properties of materials',
  ),
  chapter(
    'Electromagnetic Induction',
    'The experiments of Faraday and Henry',
    'Magnetic flux',
    "Faraday's law of induction",
    "Lenz's law and conservation of energy",
    'Motional electromotive force',
    'Inductance',
    'AC generator',
  ),
  chapter(
    'Alternating Current',
    'AC voltage applied to a resistor',
    'Representation of AC current and voltage by phasors',
    'AC voltage applied to an inductor and a capacitor',
    'AC voltage applied to a series LCR circuit',
    'Power in AC circuits: the power factor',
    'Transformers',
  ),
  chapter(
    'Electromagnetic Waves',
    'Displacement current',
    'Electromagnetic waves',
    'Electromagnetic spectrum',
  ),
  chapter(
    'Ray Optics and Optical Instruments',
    'Reflection of light by spherical mirrors',
    'Refraction',
    'Total internal reflection',
    'Refraction at spherical surfaces and by lenses',
    'Refraction through a prism',
    'Optical instruments',
  ),
  chapter(
    'Wave Optics',
    "Huygens' principle",
    'Refraction and reflection of plane waves using Huygens principle',
    'Coherent and incoherent addition of waves',
    'Interference of light waves and Young’s experiment',
    'Diffraction',
    'Polarisation',
  ),
  chapter(
    'Dual Nature of Radiation and Matter',
    'Electron emission',
    'Photoelectric effect',
    'Experimental study of the photoelectric effect',
    'Photoelectric effect and the wave theory of light',
    "Einstein's photoelectric equation",
    'Wave nature of matter',
  ),
  chapter(
    'Atoms',
    'Alpha-particle scattering and Rutherford’s nuclear model',
    'Atomic spectra',
    'Bohr model of the hydrogen atom',
    'The line spectra of the hydrogen atom',
    "de Broglie's explanation of Bohr's second postulate",
  ),
  chapter(
    'Nuclei',
    'Atomic masses and the composition of the nucleus',
    'Size of the nucleus',
    'Mass-energy and nuclear binding energy',
    'Nuclear force',
    'Radioactivity',
    'Nuclear energy',
  ),
  chapter(
    'Semiconductor Electronics',
    'Classification of metals, conductors and semiconductors',
    'Intrinsic and extrinsic semiconductors',
    'p-n junction',
    'Semiconductor diode',
    'Application of junction diode as a rectifier',
    'Special purpose p-n junction diodes',
  ),
);

export const class12Chemistry = subject(
  'Chemistry',
  chapter(
    'Solutions',
    'Types of solutions',
    'Expressing concentration of solutions',
    'Solubility',
    'Vapour pressure of liquid solutions',
    'Ideal and non-ideal solutions',
    'Colligative properties and determination of molar mass',
    'Abnormal molar masses',
  ),
  chapter(
    'Electrochemistry',
    'Electrochemical cells',
    'Galvanic cells',
    'Nernst equation',
    'Conductance of electrolytic solutions',
    'Electrolytic cells and electrolysis',
    'Batteries',
    'Fuel cells',
    'Corrosion',
  ),
  chapter(
    'Chemical Kinetics',
    'Rate of a chemical reaction',
    'Factors influencing rate of a reaction',
    'Integrated rate equations',
    'Temperature dependence of the rate of a reaction',
    'Collision theory of chemical reactions',
  ),
  chapter(
    'The d- and f-Block Elements',
    'Position in the periodic table',
    'Electronic configuration',
    'General properties of the transition elements',
    'Some important compounds of transition elements',
    'The lanthanoids',
    'The actinoids',
  ),
  chapter(
    'Coordination Compounds',
    'Werner’s theory of coordination compounds',
    'Definitions of some important terms',
    'Nomenclature of coordination compounds',
    'Isomerism in coordination compounds',
    'Bonding in coordination compounds',
    'Importance and applications',
  ),
  chapter(
    'Haloalkanes and Haloarenes',
    'Classification',
    'Nomenclature',
    'Nature of C-X bond',
    'Methods of preparation',
    'Physical and chemical properties',
    'Polyhalogen compounds',
  ),
  chapter(
    'Alcohols, Phenols and Ethers',
    'Classification',
    'Nomenclature',
    'Structures of functional groups',
    'Alcohols and phenols',
    'Some commercially important alcohols',
    'Ethers',
  ),
  chapter(
    'Aldehydes, Ketones and Carboxylic Acids',
    'Nomenclature and structure of the carbonyl group',
    'Preparation of aldehydes and ketones',
    'Physical and chemical properties',
    'Uses of aldehydes and ketones',
    'Nomenclature and structure of carboxyl group',
    'Preparation and properties of carboxylic acids',
  ),
  chapter(
    'Amines',
    'Structure of amines',
    'Classification',
    'Nomenclature',
    'Preparation of amines',
    'Physical and chemical properties',
    'Method of preparation of diazonium salts',
    'Importance of diazonium salts in synthesis',
  ),
  chapter('Biomolecules', 'Carbohydrates', 'Proteins', 'Enzymes', 'Vitamins', 'Nucleic acids'),
);

export const class12Mathematics = subject(
  'Mathematics',
  chapter(
    'Relations and Functions',
    'Types of relations',
    'Types of functions',
    'Composition of functions and invertible function',
  ),
  chapter(
    'Inverse Trigonometric Functions',
    'Basic concepts',
    'Properties of inverse trigonometric functions',
  ),
  chapter(
    'Matrices',
    'Types of matrices',
    'Operations on matrices',
    'Transpose of a matrix',
    'Symmetric and skew symmetric matrices',
    'Invertible matrices',
  ),
  chapter(
    'Determinants',
    'Determinant',
    'Properties of determinants',
    'Area of a triangle',
    'Minors and cofactors',
    'Adjoint and inverse of a matrix',
    'Applications of determinants and matrices',
  ),
  chapter(
    'Continuity and Differentiability',
    'Continuity',
    'Differentiability',
    'Exponential and logarithmic functions',
    'Logarithmic differentiation',
    'Derivatives of functions in parametric forms',
    'Second order derivative',
  ),
  chapter(
    'Application of Derivatives',
    'Rate of change of quantities',
    'Increasing and decreasing functions',
    'Maxima and minima',
  ),
  chapter(
    'Integrals',
    'Integration as an inverse process of differentiation',
    'Methods of integration',
    'Integrals of some particular functions',
    'Integration by partial fractions',
    'Integration by parts',
    'Definite integral',
    'Fundamental theorem of calculus',
    'Evaluation of definite integrals by substitution',
    'Some properties of definite integrals',
  ),
  chapter('Application of Integrals', 'Area under simple curves', 'Area between two curves'),
  chapter(
    'Differential Equations',
    'Basic concepts',
    'General and particular solutions',
    'Formation of a differential equation',
    'Methods of solving first order, first degree differential equations',
  ),
  chapter(
    'Vector Algebra',
    'Some basic concepts',
    'Types of vectors',
    'Addition of vectors',
    'Multiplication of a vector by a scalar',
    'Product of two vectors',
  ),
  chapter(
    'Three Dimensional Geometry',
    'Direction cosines and direction ratios of a line',
    'Equation of a line in space',
    'Angle between two lines',
    'Shortest distance between two lines',
  ),
  chapter(
    'Linear Programming',
    'Linear programming problem and its mathematical formulation',
    'Different types of linear programming problems',
  ),
  chapter(
    'Probability',
    'Conditional probability',
    'Multiplication theorem on probability',
    'Independent events',
    'Bayes’ theorem',
    'Random variables and their probability distributions',
  ),
);

export const class12Biology = subject(
  'Biology',
  chapter(
    'Sexual Reproduction in Flowering Plants',
    'Flower — a fascinating organ',
    'Pre-fertilisation: structures and events',
    'Double fertilisation',
    'Post-fertilisation: structures and events',
    'Apomixis and polyembryony',
  ),
  chapter(
    'Human Reproduction',
    'The male reproductive system',
    'The female reproductive system',
    'Gametogenesis',
    'Menstrual cycle',
    'Fertilisation and implantation',
    'Pregnancy and embryonic development',
    'Parturition and lactation',
  ),
  chapter(
    'Reproductive Health',
    'Reproductive health — problems and strategies',
    'Population stabilisation and birth control',
    'Medical termination of pregnancy',
    'Sexually transmitted infections',
    'Infertility',
  ),
  chapter(
    'Principles of Inheritance and Variation',
    "Mendel's laws of inheritance",
    'Inheritance of one gene',
    'Inheritance of two genes',
    'Sex determination',
    'Mutation',
    'Genetic disorders',
  ),
  chapter(
    'Molecular Basis of Inheritance',
    'The DNA',
    'The search for genetic material',
    'RNA world',
    'Replication',
    'Transcription',
    'Genetic code',
    'Translation',
    'Regulation of gene expression',
    'Human genome project',
    'DNA fingerprinting',
  ),
  chapter(
    'Evolution',
    'Origin of life',
    'Evolution of life forms',
    'Evidences for evolution',
    'Adaptive radiation',
    'Biological evolution',
    'Mechanism of evolution',
    'Hardy-Weinberg principle',
    'Origin and evolution of man',
  ),
  chapter(
    'Human Health and Disease',
    'Common diseases in humans',
    'Immunity',
    'AIDS',
    'Cancer',
    'Drugs and alcohol abuse',
  ),
  chapter(
    'Microbes in Human Welfare',
    'Microbes in household products',
    'Microbes in industrial products',
    'Microbes in sewage treatment',
    'Microbes in the production of biogas',
    'Microbes as biocontrol agents',
    'Microbes as biofertilisers',
  ),
  chapter(
    'Biotechnology: Principles and Processes',
    'Principles of biotechnology',
    'Tools of recombinant DNA technology',
    'Processes of recombinant DNA technology',
  ),
  chapter(
    'Biotechnology and its Applications',
    'Biotechnological applications in agriculture',
    'Biotechnological applications in medicine',
    'Transgenic animals',
    'Ethical issues',
  ),
  chapter(
    'Organisms and Populations',
    'Organism and its environment',
    'Populations',
    'Population attributes',
    'Population growth',
    'Population interactions',
  ),
  chapter(
    'Ecosystem',
    'Ecosystem — structure and function',
    'Productivity',
    'Decomposition',
    'Energy flow',
    'Ecological pyramids',
  ),
  chapter(
    'Biodiversity and Conservation',
    'Biodiversity',
    'Patterns of biodiversity',
    'Loss of biodiversity',
    'Biodiversity conservation',
  ),
);

export const class11English = subject(
  'English',
  chapter(
    'Hornbill: Prose',
    'The Portrait of a Lady',
    'We’re Not Afraid to Die… if We Can All Be Together',
    'Discovering Tut: the Saga Continues',
    'The Ailing Planet: the Green Movement’s Role',
    'The Browning Version',
  ),
  chapter(
    'Hornbill: Poetry',
    'A Photograph',
    'The Laburnum Top',
    'The Voice of the Rain',
    'Childhood',
    'Father to Son',
  ),
  chapter(
    'Snapshots: Supplementary Reader',
    'The Summer of the Beautiful White Horse',
    'The Address',
    'Mother’s Day',
    'Birth',
    'The Tale of Melon City',
  ),
  chapter(
    'Reading and Writing Skills',
    'Note making and summarising',
    'Notice, poster and advertisement',
    'Letters',
    'Article and report writing',
  ),
);

export const class12English = subject(
  'English',
  chapter(
    'Flamingo: Prose',
    'The Last Lesson',
    'Lost Spring',
    'Deep Water',
    'The Rattrap',
    'Indigo',
    'Poets and Pancakes',
    'The Interview',
    'Going Places',
  ),
  chapter(
    'Flamingo: Poetry',
    'My Mother at Sixty-six',
    'Keeping Quiet',
    'A Thing of Beauty',
    'A Roadside Stand',
    'Aunt Jennifer’s Tigers',
  ),
  chapter(
    'Vistas: Supplementary Reader',
    'The Third Level',
    'The Tiger King',
    'Journey to the End of the Earth',
    'The Enemy',
    'On the Face of It',
    'Memories of Childhood',
  ),
  chapter(
    'Reading and Writing Skills',
    'Note making and summarising',
    'Notice writing',
    'Letters',
    'Article and report writing',
  ),
);
