import { chapter, subject } from './builder';

/**
 * CBSE classes 9 and 10, following the current rationalised NCERT books.
 *
 * Chapters are the NCERT chapters in book order, because that is the order a
 * student is taught them and the order their school tests them in. Chapters
 * dropped in the 2023-24 rationalisation are left out rather than kept "just in
 * case" — a syllabus listing work nobody is examined on wastes the time it was
 * meant to save.
 */

// ---------------------------------------------------------------------------
// Class 9
// ---------------------------------------------------------------------------

export const class9Mathematics = subject(
  'Mathematics',
  chapter(
    'Number Systems',
    'Irrational numbers',
    'Real numbers and their decimal expansions',
    'Operations on real numbers',
    'Laws of exponents for real numbers',
  ),
  chapter(
    'Polynomials',
    'Polynomials in one variable',
    'Zeroes of a polynomial',
    'Factorisation of polynomials',
    'Algebraic identities',
  ),
  chapter('Coordinate Geometry', 'The Cartesian system', 'Plotting a point in the plane'),
  chapter(
    'Linear Equations in Two Variables',
    'Linear equations',
    'Solution of a linear equation',
    'Graph of a linear equation in two variables',
  ),
  chapter(
    "Introduction to Euclid's Geometry",
    "Euclid's definitions, axioms and postulates",
    'Equivalent versions of the fifth postulate',
  ),
  chapter(
    'Lines and Angles',
    'Basic terms and definitions',
    'Intersecting and non-intersecting lines',
    'Pairs of angles',
    'Lines parallel to the same line',
    'Angle sum property of a triangle',
  ),
  chapter(
    'Triangles',
    'Congruence of triangles',
    'Criteria for congruence',
    'Properties of a triangle',
    'Inequalities in a triangle',
  ),
  chapter(
    'Quadrilaterals',
    'Angle sum property of a quadrilateral',
    'Types of quadrilaterals',
    'Properties of a parallelogram',
    'The mid-point theorem',
  ),
  chapter(
    'Circles',
    'Angle subtended by a chord at a point',
    'Perpendicular from the centre to a chord',
    'Equal chords and their distances from the centre',
    'Angle subtended by an arc',
    'Cyclic quadrilaterals',
  ),
  chapter(
    "Heron's Formula",
    'Area of a triangle by Heron’s formula',
    'Application in finding areas of quadrilaterals',
  ),
  chapter(
    'Surface Areas and Volumes',
    'Surface area of a right circular cone',
    'Surface area of a sphere',
    'Volume of a right circular cone',
    'Volume of a sphere',
  ),
  chapter(
    'Statistics',
    'Collection of data',
    'Presentation of data',
    'Graphical representation of data',
  ),
);

export const class9Science = subject(
  'Science',
  chapter(
    'Matter in Our Surroundings',
    'Physical nature of matter',
    'Characteristics of particles of matter',
    'States of matter',
    'Change of state',
    'Evaporation',
  ),
  chapter(
    'Is Matter Around Us Pure',
    'Mixtures and solutions',
    'Concentration of a solution',
    'Suspensions and colloids',
    'Separating the components of a mixture',
    'Physical and chemical changes',
    'Types of pure substances',
  ),
  chapter(
    'Atoms and Molecules',
    'Laws of chemical combination',
    'Atoms and their symbols',
    'Atomic mass',
    'Molecules and ions',
    'Writing chemical formulae',
    'Molecular mass and mole concept',
  ),
  chapter(
    'Structure of the Atom',
    'Charged particles in matter',
    "Thomson's model",
    "Rutherford's model",
    "Bohr's model",
    'Neutrons',
    'Distribution of electrons in shells',
    'Valency',
    'Atomic number and mass number',
    'Isotopes and isobars',
  ),
  chapter(
    'The Fundamental Unit of Life',
    'Cell as the basic unit of life',
    'Structural organisation of a cell',
    'Plasma membrane',
    'Cell wall',
    'Nucleus',
    'Cytoplasm and cell organelles',
  ),
  chapter(
    'Tissues',
    'Plant tissues',
    'Meristematic and permanent tissue',
    'Animal tissues',
    'Epithelial, connective, muscular and nervous tissue',
  ),
  chapter(
    'Motion',
    'Describing motion',
    'Measuring the rate of motion',
    'Rate of change of velocity',
    'Graphical representation of motion',
    'Equations of motion',
    'Uniform circular motion',
  ),
  chapter(
    'Force and Laws of Motion',
    'Balanced and unbalanced forces',
    "Newton's first law",
    "Newton's second law",
    "Newton's third law",
    'Inertia and mass',
    'Conservation of momentum',
  ),
  chapter(
    'Gravitation',
    'Universal law of gravitation',
    'Free fall',
    'Mass and weight',
    'Thrust and pressure',
    "Archimedes' principle",
    'Relative density',
  ),
  chapter(
    'Work and Energy',
    'Work done by a constant force',
    'Kinetic energy',
    'Potential energy',
    'Law of conservation of energy',
    'Rate of doing work: power',
  ),
  chapter(
    'Sound',
    'Production and propagation of sound',
    'Characteristics of a sound wave',
    'Speed of sound',
    'Reflection of sound',
    'Range of hearing',
    'Applications of ultrasound',
  ),
  chapter(
    'Improvement in Food Resources',
    'Improvement in crop yields',
    'Crop variety improvement',
    'Crop production management',
    'Crop protection management',
    'Animal husbandry',
  ),
);

export const class9SocialScience = subject(
  'Social Science',
  chapter(
    'History: The French Revolution',
    'French society in the late eighteenth century',
    'The outbreak of the revolution',
    'France becomes a constitutional monarchy',
    'The Reign of Terror',
    'Did women have a revolution?',
    'The abolition of slavery',
  ),
  chapter(
    'History: Socialism in Europe and the Russian Revolution',
    'The age of social change',
    'The Russian Revolution',
    'The February and October revolutions',
    'What changed after October',
    'The global influence of the revolution',
  ),
  chapter(
    'History: Nazism and the Rise of Hitler',
    'Birth of the Weimar Republic',
    'Hitler’s rise to power',
    'The Nazi worldview',
    'Youth in Nazi Germany',
    'Ordinary people and the crimes against humanity',
  ),
  chapter(
    'History: Forest Society and Colonialism',
    'Why deforestation?',
    'The rise of commercial forestry',
    'Rebellion in the forest',
    'Forest transformations in Java',
  ),
  chapter(
    'History: Pastoralists in the Modern World',
    'Pastoral nomads and their movements',
    'Colonial rule and pastoral life',
    'Pastoralism in Africa',
  ),
  chapter(
    'Geography: India — Size and Location',
    'Location and size',
    'India and the world',
    'India’s neighbours',
  ),
  chapter(
    'Geography: Physical Features of India',
    'Major physiographic divisions',
    'The Himalayan mountains',
    'The Northern Plains',
    'The Peninsular Plateau',
    'The Indian Desert',
    'The Coastal Plains and Islands',
  ),
  chapter(
    'Geography: Drainage',
    'Drainage systems in India',
    'The Himalayan rivers',
    'The Peninsular rivers',
    'Lakes',
    'Role of rivers in the economy',
    'River pollution',
  ),
  chapter(
    'Geography: Climate',
    'Climatic controls',
    'Factors affecting India’s climate',
    'The Indian monsoon',
    'The seasons',
    'Distribution of rainfall',
  ),
  chapter(
    'Geography: Natural Vegetation and Wildlife',
    'Types of vegetation',
    'Wildlife',
    'Conservation',
  ),
  chapter(
    'Geography: Population',
    'Population size and distribution',
    'Population growth and processes of change',
    'Age composition, sex ratio and literacy',
    'Occupational structure and health',
  ),
  chapter(
    'Civics: What is Democracy? Why Democracy?',
    'What is democracy?',
    'Features of democracy',
    'Why democracy?',
    'Broader meanings of democracy',
  ),
  chapter(
    'Civics: Constitutional Design',
    'Democratic constitution in South Africa',
    'Why do we need a constitution?',
    'Making of the Indian Constitution',
    'Guiding values of the Indian Constitution',
  ),
  chapter(
    'Civics: Electoral Politics',
    'Why elections?',
    'What is our system of elections?',
    'What makes elections in India democratic?',
  ),
  chapter(
    'Civics: Working of Institutions',
    'How is a major policy decision taken?',
    'Parliament',
    'Political executive',
    'The judiciary',
  ),
  chapter(
    'Civics: Democratic Rights',
    'Life without rights',
    'Rights in a democracy',
    'Fundamental rights in the Indian Constitution',
    'Securing fundamental rights',
  ),
  chapter(
    'Economics: The Story of Village Palampur',
    'Organisation of production',
    'Farming in Palampur',
    'Non-farm activities in Palampur',
  ),
  chapter(
    'Economics: People as Resource',
    'Economic activities by men and women',
    'Quality of population',
    'Unemployment',
  ),
  chapter(
    'Economics: Poverty as a Challenge',
    'Two typical cases of poverty',
    'Poverty as seen by social scientists',
    'Poverty estimates',
    'Vulnerable groups',
    'Causes and anti-poverty measures',
  ),
  chapter(
    'Economics: Food Security in India',
    'What is food security?',
    'Why food security?',
    'Who are food insecure?',
    'Food security in India',
    'Role of cooperatives',
  ),
);

export const class9English = subject(
  'English',
  chapter(
    'Beehive: Prose',
    'The Fun They Had',
    'The Sound of Music',
    'The Little Girl',
    'A Truly Beautiful Mind',
    'The Snake and the Mirror',
    'My Childhood',
    'Reach for the Top',
    'Kathmandu',
    'If I Were You',
  ),
  chapter(
    'Beehive: Poetry',
    'The Road Not Taken',
    'Wind',
    'Rain on the Roof',
    'The Lake Isle of Innisfree',
    'A Legend of the Northland',
    'No Men Are Foreign',
    'On Killing a Tree',
    'The Snake Trying',
    'A Slumber Did My Spirit Seal',
  ),
  chapter(
    'Moments: Supplementary Reader',
    'The Lost Child',
    'The Adventures of Toto',
    'Iswaran the Storyteller',
    'In the Kingdom of Fools',
    'The Happy Prince',
    'Weathering the Storm in Ersama',
    'The Last Leaf',
    'A House Is Not a Home',
    'The Beggar',
  ),
  chapter('Grammar', 'Tenses', 'Modals', 'Subject-verb concord', 'Reported speech', 'Determiners'),
  chapter('Writing Skills', 'Descriptive paragraph', 'Story writing', 'Diary entry'),
);

// ---------------------------------------------------------------------------
// Class 10
// ---------------------------------------------------------------------------

export const class10Mathematics = subject(
  'Mathematics',
  chapter('Real Numbers', 'The fundamental theorem of arithmetic', 'Revisiting irrational numbers'),
  chapter(
    'Polynomials',
    'Geometrical meaning of the zeroes of a polynomial',
    'Relationship between zeroes and coefficients',
  ),
  chapter(
    'Pair of Linear Equations in Two Variables',
    'Graphical method of solution',
    'Substitution method',
    'Elimination method',
    'Equations reducible to a pair of linear equations',
  ),
  chapter(
    'Quadratic Equations',
    'Solution by factorisation',
    'Solution by completing the square',
    'Nature of roots',
  ),
  chapter('Arithmetic Progressions', 'nth term of an AP', 'Sum of first n terms of an AP'),
  chapter(
    'Triangles',
    'Similar figures',
    'Similarity of triangles',
    'Criteria for similarity of triangles',
  ),
  chapter('Coordinate Geometry', 'Distance formula', 'Section formula'),
  chapter(
    'Introduction to Trigonometry',
    'Trigonometric ratios',
    'Trigonometric ratios of some specific angles',
    'Trigonometric identities',
  ),
  chapter('Some Applications of Trigonometry', 'Heights and distances'),
  chapter('Circles', 'Tangent to a circle', 'Number of tangents from a point on a circle'),
  chapter('Areas Related to Circles', 'Areas of sector and segment of a circle'),
  chapter(
    'Surface Areas and Volumes',
    'Surface area of a combination of solids',
    'Volume of a combination of solids',
  ),
  chapter('Statistics', 'Mean of grouped data', 'Mode of grouped data', 'Median of grouped data'),
  chapter('Probability', 'Theoretical probability', 'Simple problems on single events'),
);

export const class10Science = subject(
  'Science',
  chapter(
    'Chemical Reactions and Equations',
    'Chemical equations',
    'Balancing chemical equations',
    'Types of chemical reactions',
    'Effects of oxidation reactions in everyday life',
  ),
  chapter(
    'Acids, Bases and Salts',
    'Chemical properties of acids and bases',
    'What do all acids and bases have in common?',
    'How strong are acid or base solutions?',
    'More about salts',
  ),
  chapter(
    'Metals and Non-metals',
    'Physical properties',
    'Chemical properties of metals',
    'How do metals and non-metals react?',
    'Occurrence of metals',
    'Corrosion',
  ),
  chapter(
    'Carbon and its Compounds',
    'Bonding in carbon',
    'Versatile nature of carbon',
    'Chemical properties of carbon compounds',
    'Some important carbon compounds',
  ),
  chapter('Life Processes', 'Nutrition', 'Respiration', 'Transportation', 'Excretion'),
  chapter(
    'Control and Coordination',
    'Animals — nervous system',
    'Reflex action',
    'Human brain',
    'Coordination in plants',
    'Hormones in animals',
  ),
  chapter(
    'How do Organisms Reproduce?',
    'Do organisms create exact copies of themselves?',
    'Modes of reproduction in unicellular organisms',
    'Sexual reproduction',
    'Reproductive health',
  ),
  chapter(
    'Heredity',
    'Accumulation of variation during reproduction',
    'Heredity',
    "Mendel's contribution",
    'Sex determination',
  ),
  chapter(
    'Light — Reflection and Refraction',
    'Reflection of light',
    'Spherical mirrors',
    'Image formation by spherical mirrors',
    'Mirror formula and magnification',
    'Refraction of light',
    'Refraction by spherical lenses',
    'Lens formula and power of a lens',
  ),
  chapter(
    'The Human Eye and the Colourful World',
    'The human eye',
    'Defects of vision and their correction',
    'Refraction of light through a prism',
    'Dispersion of white light',
    'Atmospheric refraction',
    'Scattering of light',
  ),
  chapter(
    'Electricity',
    'Electric current and circuit',
    'Electric potential and potential difference',
    "Ohm's law",
    'Factors on which resistance depends',
    'Resistors in series and parallel',
    'Heating effect of electric current',
    'Electric power',
  ),
  chapter(
    'Magnetic Effects of Electric Current',
    'Magnetic field and field lines',
    'Magnetic field due to a current-carrying conductor',
    'Force on a current-carrying conductor',
    'Electric motor',
    'Electromagnetic induction',
    'Electric generator',
    'Domestic electric circuits',
  ),
  chapter(
    'Our Environment',
    'Ecosystem and its components',
    'Food chains and webs',
    'How do our activities affect the environment?',
    'Ozone layer and waste management',
  ),
);

export const class10SocialScience = subject(
  'Social Science',
  chapter(
    'History: The Rise of Nationalism in Europe',
    'The French Revolution and the idea of the nation',
    'The making of nationalism in Europe',
    'The age of revolutions',
    'The making of Germany and Italy',
    'Visualising the nation',
    'Nationalism and imperialism',
  ),
  chapter(
    'History: Nationalism in India',
    'The First World War, Khilafat and Non-Cooperation',
    'Differing strands within the movement',
    'Towards the Civil Disobedience Movement',
    'The sense of collective belonging',
  ),
  chapter(
    'History: The Making of a Global World',
    'The pre-modern world',
    'The nineteenth century',
    'The inter-war economy',
    'Rebuilding a world economy',
  ),
  chapter(
    'History: The Age of Industrialisation',
    'Before the industrial revolution',
    'Hand labour and steam power',
    'Industrialisation in the colonies',
    'Factories come up',
    'The peculiarities of industrial growth',
    'Market for goods',
  ),
  chapter(
    'History: Print Culture and the Modern World',
    'The first printed books',
    'Print comes to Europe',
    'The print revolution and its impact',
    'The reading mania',
    'The nineteenth century',
    'India and the world of print',
    'Print and censorship',
  ),
  chapter(
    'Geography: Resources and Development',
    'Types of resources',
    'Development of resources',
    'Resource planning in India',
    'Land resources and land use',
    'Soil as a resource',
  ),
  chapter(
    'Geography: Forest and Wildlife Resources',
    'Biodiversity in India',
    'Conservation of forest and wildlife',
    'Types and distribution of forests',
    'Community and conservation',
  ),
  chapter(
    'Geography: Water Resources',
    'Water scarcity and the need for conservation',
    'Multi-purpose river projects',
    'Rainwater harvesting',
  ),
  chapter(
    'Geography: Agriculture',
    'Types of farming',
    'Cropping pattern',
    'Major crops',
    'Technological and institutional reforms',
    'Impact of globalisation on agriculture',
  ),
  chapter(
    'Geography: Minerals and Energy Resources',
    'What is a mineral?',
    'Mode of occurrence of minerals',
    'Ferrous and non-ferrous minerals',
    'Conservation of minerals',
    'Conventional and non-conventional sources of energy',
  ),
  chapter(
    'Geography: Manufacturing Industries',
    'Importance of manufacturing',
    'Contribution of industry to the national economy',
    'Classification of industries',
    'Industrial pollution and environmental degradation',
  ),
  chapter(
    'Geography: Lifelines of National Economy',
    'Roadways and railways',
    'Pipelines and waterways',
    'Airways',
    'Communication',
    'International trade and tourism',
  ),
  chapter(
    'Civics: Power-sharing',
    'Case studies of Belgium and Sri Lanka',
    'Why power sharing is desirable',
    'Forms of power sharing',
  ),
  chapter(
    'Civics: Federalism',
    'What is federalism?',
    'What makes India a federal country?',
    'How is federalism practised?',
    'Decentralisation in India',
  ),
  chapter(
    'Civics: Gender, Religion and Caste',
    'Gender and politics',
    'Religion, communalism and politics',
    'Caste and politics',
  ),
  chapter(
    'Civics: Political Parties',
    'Why do we need political parties?',
    'How many parties should we have?',
    'National and state parties',
    'Challenges to political parties',
    'How can parties be reformed?',
  ),
  chapter(
    'Civics: Outcomes of Democracy',
    'How do we assess democracy’s outcomes?',
    'Accountable, responsive and legitimate government',
    'Economic growth and development',
    'Reduction of inequality and poverty',
    'Dignity and freedom of the citizens',
  ),
  chapter(
    'Economics: Development',
    'What development promises',
    'Income and other goals',
    'National development',
    'Public facilities',
    'Sustainability of development',
  ),
  chapter(
    'Economics: Sectors of the Indian Economy',
    'Sectors of economic activities',
    'Comparing the three sectors',
    'Division of sectors as organised and unorganised',
    'Sectors in terms of ownership',
  ),
  chapter(
    'Economics: Money and Credit',
    'Money as a medium of exchange',
    'Modern forms of money',
    'Loan activities of banks',
    'Two different credit situations',
    'Formal and informal sector credit',
    'Self-help groups for the poor',
  ),
  chapter(
    'Economics: Globalisation and the Indian Economy',
    'Production across countries',
    'Interlinking production across countries',
    'Foreign trade and integration of markets',
    'What is globalisation?',
    'Factors that have enabled globalisation',
    'The struggle for a fair globalisation',
  ),
  chapter(
    'Economics: Consumer Rights',
    'The consumer in the marketplace',
    'Consumer movement',
    'Consumer rights',
    'Taking the consumer movement forward',
  ),
);

export const class10English = subject(
  'English',
  chapter(
    'First Flight: Prose',
    'A Letter to God',
    'Nelson Mandela: Long Walk to Freedom',
    'Two Stories about Flying',
    'From the Diary of Anne Frank',
    'Glimpses of India',
    'Mijbil the Otter',
    'Madam Rides the Bus',
    'The Sermon at Benares',
    'The Proposal',
  ),
  chapter(
    'First Flight: Poetry',
    'Dust of Snow',
    'Fire and Ice',
    'A Tiger in the Zoo',
    'How to Tell Wild Animals',
    'The Ball Poem',
    'Amanda!',
    'The Trees',
    'Fog',
    'The Tale of Custard the Dragon',
    'For Anne Gregory',
  ),
  chapter(
    'Footprints without Feet: Supplementary Reader',
    'A Triumph of Surgery',
    'The Thief’s Story',
    'The Midnight Visitor',
    'A Question of Trust',
    'Footprints without Feet',
    'The Making of a Scientist',
    'The Necklace',
    'Bholi',
    'The Book That Saved the Earth',
  ),
  chapter('Grammar', 'Tenses', 'Modals', 'Subject-verb concord', 'Reported speech', 'Determiners'),
  chapter('Writing Skills', 'Formal letter', 'Analytical paragraph'),
);
