import type { SyllabusTemplate } from '../template';
import { chapter, subject } from './builder';

/**
 * Competitive examinations.
 *
 * Where an exam is organised by paper rather than by subject — UPSC, SSC — the
 * papers are the subjects, because a candidate revises and is scored per paper.
 * Where it is organised by discipline — NEET PG, GATE — the disciplines are.
 */

export const upscCse: SyllabusTemplate = {
  id: 'upsc-cse',
  name: 'UPSC Civil Services',
  description: 'Prelims and Mains: GS Papers I to IV, CSAT and Essay.',
  category: 'exam',
  source: 'UPSC Civil Services Examination notification, transcribed for PrepPilot.',
  verified: true,
  subjects: [
    subject(
      'Prelims: General Studies Paper I',
      chapter(
        'Current Events of National and International Importance',
        'National current affairs',
        'International relations and current affairs',
        'Government schemes and policies',
        'Reports and indices',
      ),
      chapter(
        'History of India and the Indian National Movement',
        'Ancient India',
        'Medieval India',
        'Modern India',
        'Art and culture',
        'The Indian national movement',
      ),
      chapter(
        'Indian and World Geography',
        'Physical geography',
        'Indian geography',
        'World geography',
        'Economic geography',
        'Map-based questions',
      ),
      chapter(
        'Indian Polity and Governance',
        'Constitution and its features',
        'Political system and panchayati raj',
        'Public policy and rights issues',
        'Constitutional and non-constitutional bodies',
      ),
      chapter(
        'Economic and Social Development',
        'Sustainable development',
        'Poverty and inclusion',
        'Demographics and social sector initiatives',
        'Basic economics and the budget',
      ),
      chapter(
        'Environment, Biodiversity and Climate Change',
        'Ecology and ecosystems',
        'Biodiversity and conservation',
        'Climate change and international agreements',
        'Pollution and environmental governance',
      ),
      chapter(
        'General Science',
        'Physics, chemistry and biology fundamentals',
        'Science and technology developments',
        'Space and defence technology',
        'Biotechnology and health',
      ),
    ),
    subject(
      'Prelims: CSAT (Paper II)',
      chapter(
        'Comprehension',
        'Reading comprehension passages',
        'Inference and assumption questions',
      ),
      chapter(
        'Interpersonal Skills and Communication',
        'Interpersonal skills',
        'Communication skills',
      ),
      chapter(
        'Logical Reasoning and Analytical Ability',
        'Syllogisms and statements',
        'Seating arrangements and puzzles',
        'Blood relations and directions',
        'Series and coding-decoding',
      ),
      chapter(
        'Decision Making and Problem Solving',
        'Decision making scenarios',
        'Problem solving approaches',
      ),
      chapter(
        'General Mental Ability',
        'Number system',
        'Percentages, ratio and proportion',
        'Time, speed and distance',
        'Time and work',
        'Averages and mixtures',
      ),
      chapter(
        'Basic Numeracy and Data Interpretation',
        'Basic numeracy up to class X level',
        'Tables, charts and graphs',
        'Data sufficiency',
      ),
    ),
    subject(
      'Mains: Essay',
      chapter(
        'Essay Writing',
        'Structure and approach to an essay',
        'Philosophical and abstract topics',
        'Social and economic topics',
        'Polity and governance topics',
        'Answer enrichment and practice',
      ),
    ),
    subject(
      'Mains: General Studies Paper I',
      chapter(
        'Indian Heritage and Culture',
        'Art forms, literature and architecture from ancient to modern times',
        'Salient aspects of Indian culture',
      ),
      chapter(
        'Modern Indian History',
        'Events from the middle of the eighteenth century',
        'The Freedom Struggle and its stages',
        'Important personalities and their contributions',
      ),
      chapter(
        'Post-Independence India',
        'Consolidation and reorganisation within the country',
        'Post-independence political and economic developments',
      ),
      chapter(
        'World History',
        'Industrial revolution',
        'World wars',
        'Colonisation and decolonisation',
        'Political philosophies: communism, capitalism and socialism',
      ),
      chapter(
        'Indian Society',
        'Salient features of Indian society and diversity',
        'Role of women and women’s organisations',
        'Population and associated issues',
        'Poverty and developmental issues',
        'Urbanisation, their problems and remedies',
        'Effects of globalisation on Indian society',
        'Social empowerment, communalism, regionalism and secularism',
      ),
      chapter(
        'Geography of the World and Society',
        'Salient features of world physical geography',
        'Distribution of key natural resources',
        'Factors for the location of industries',
        'Geophysical phenomena',
        'Changes in critical geographical features',
      ),
    ),
    subject(
      'Mains: General Studies Paper II',
      chapter(
        'Constitution and Polity',
        'Indian Constitution: historical underpinnings and features',
        'Functions and responsibilities of the Union and the States',
        'Separation of powers and dispute redressal',
        'Comparison with other countries',
      ),
      chapter(
        'Parliament, Judiciary and Executive',
        'Structure and functioning of the parliament and state legislatures',
        'Structure and functioning of the executive and judiciary',
        'Ministries and departments',
        'Pressure groups and formal or informal associations',
      ),
      chapter(
        'Governance and Transparency',
        'Government policies and interventions',
        'Development processes and the role of NGOs and SHGs',
        'Transparency and accountability, e-governance',
        'Citizens charters and institutional measures',
        'Role of civil services in a democracy',
      ),
      chapter(
        'Social Justice and Welfare',
        'Welfare schemes for vulnerable sections',
        'Issues relating to development and management of health, education and human resources',
        'Issues relating to poverty and hunger',
      ),
      chapter(
        'International Relations',
        'India and its neighbourhood',
        'Bilateral, regional and global groupings',
        'Effect of policies of developed and developing countries on India',
        'Important international institutions and agencies',
      ),
    ),
    subject(
      'Mains: General Studies Paper III',
      chapter(
        'Indian Economy and Planning',
        'Indian economy and issues relating to planning',
        'Mobilisation of resources, growth and development',
        'Inclusive growth and issues arising from it',
        'Government budgeting',
      ),
      chapter(
        'Agriculture and Food Processing',
        'Major cropping patterns and irrigation systems',
        'Issues of buffer stocks and food security',
        'Public distribution system',
        'Food processing and related industries',
        'Land reforms in India',
      ),
      chapter(
        'Infrastructure and Industrial Policy',
        'Effects of liberalisation on the economy',
        'Changes in industrial policy',
        'Infrastructure: energy, ports, roads, airports and railways',
        'Investment models',
      ),
      chapter(
        'Science and Technology',
        'Developments and their applications and effects in everyday life',
        'Achievements of Indians in science and technology',
        'Awareness in IT, space, computers, robotics and nano-technology',
        'Issues relating to intellectual property rights',
      ),
      chapter(
        'Environment and Disaster Management',
        'Conservation, environmental pollution and degradation',
        'Environmental impact assessment',
        'Disaster and disaster management',
      ),
      chapter(
        'Internal Security',
        'Linkages between development and the spread of extremism',
        'Role of external state and non-state actors',
        'Challenges through communication networks and cyber security',
        'Money laundering and its prevention',
        'Security challenges in border areas',
        'Various security forces and agencies and their mandate',
      ),
    ),
    subject(
      'Mains: General Studies Paper IV (Ethics, Integrity and Aptitude)',
      chapter(
        'Ethics and Human Interface',
        'Essence, determinants and consequences of ethics in human action',
        'Dimensions of ethics',
        'Ethics in private and public relationships',
        'Human values and lessons from great leaders',
        'Role of family, society and educational institutions',
      ),
      chapter(
        'Attitude',
        'Content, structure and function of attitude',
        'Its influence and relation with thought and behaviour',
        'Moral and political attitudes',
        'Social influence and persuasion',
      ),
      chapter(
        'Aptitude and Foundational Values for Civil Service',
        'Integrity and impartiality',
        'Non-partisanship and objectivity',
        'Dedication to public service',
        'Empathy, tolerance and compassion towards the weaker sections',
      ),
      chapter(
        'Emotional Intelligence',
        'Concepts of emotional intelligence',
        'Utilities and application in administration and governance',
      ),
      chapter(
        'Contributions of Moral Thinkers and Philosophers',
        'Indian moral thinkers',
        'World moral thinkers and philosophers',
      ),
      chapter(
        'Public and Civil Service Values',
        'Status and problems of ethics in public administration',
        'Ethical concerns and dilemmas in government and private institutions',
        'Laws, rules, regulations and conscience as sources of ethical guidance',
        'Accountability and ethical governance',
        'Corporate governance',
      ),
      chapter(
        'Probity in Governance',
        'Concept of public service',
        'Philosophical basis of governance and probity',
        'Right to information',
        'Codes of ethics and codes of conduct',
        'Citizen’s charters and work culture',
        'Challenges of corruption',
      ),
      chapter(
        'Case Studies',
        'Case studies on the above issues',
        'Approach and structure for case study answers',
      ),
    ),
  ],
};

export const sscCgl: SyllabusTemplate = {
  id: 'ssc-cgl',
  name: 'SSC CGL',
  description:
    'Tier 1 and Tier 2: reasoning, quantitative aptitude, English and general awareness.',
  category: 'exam',
  source: 'SSC Combined Graduate Level examination notice, transcribed for PrepPilot.',
  verified: true,
  subjects: [
    subject(
      'General Intelligence and Reasoning',
      chapter(
        'Verbal Reasoning',
        'Analogies',
        'Classification and odd one out',
        'Coding and decoding',
        'Blood relations',
        'Direction and distance',
        'Order and ranking',
        'Series completion',
      ),
      chapter(
        'Logical Reasoning',
        'Syllogism',
        'Statement and conclusion',
        'Statement and assumption',
        'Logical Venn diagrams',
        'Word formation',
        'Alphabet and number series',
      ),
      chapter(
        'Analytical Reasoning',
        'Seating arrangement',
        'Puzzles and arrangements',
        'Data sufficiency',
        'Decision making',
      ),
      chapter(
        'Non-Verbal Reasoning',
        'Figure series and analogy',
        'Mirror and water images',
        'Paper folding and cutting',
        'Embedded and hidden figures',
        'Cubes and dice',
        'Counting of figures',
      ),
    ),
    subject(
      'Quantitative Aptitude',
      chapter(
        'Number System',
        'Types of numbers',
        'LCM and HCF',
        'Divisibility rules',
        'Remainder theorem',
        'Surds and indices',
      ),
      chapter(
        'Arithmetic: Ratio and Percentage',
        'Percentage',
        'Ratio and proportion',
        'Partnership',
        'Mixture and alligation',
        'Average',
      ),
      chapter(
        'Arithmetic: Commercial Mathematics',
        'Profit and loss',
        'Discount',
        'Simple interest',
        'Compound interest',
      ),
      chapter(
        'Arithmetic: Time and Work',
        'Time and work',
        'Pipes and cisterns',
        'Time, speed and distance',
        'Boats and streams',
        'Trains',
      ),
      chapter(
        'Algebra',
        'Basic algebraic identities',
        'Linear equations in two variables',
        'Quadratic equations',
        'Graphs of linear equations',
      ),
      chapter(
        'Geometry',
        'Lines and angles',
        'Triangles and their properties',
        'Congruence and similarity',
        'Quadrilaterals and polygons',
        'Circles, chords and tangents',
      ),
      chapter(
        'Mensuration',
        'Areas of plane figures',
        'Surface area and volume of solids',
        'Prism, cylinder, cone and sphere',
      ),
      chapter(
        'Trigonometry',
        'Trigonometric ratios and identities',
        'Complementary angles',
        'Heights and distances',
      ),
      chapter(
        'Data Interpretation',
        'Tables',
        'Bar graphs and line charts',
        'Pie charts',
        'Mixed and caselet data interpretation',
      ),
    ),
    subject(
      'English Language and Comprehension',
      chapter(
        'Grammar',
        'Parts of speech',
        'Tenses',
        'Subject-verb agreement',
        'Articles and prepositions',
        'Narration',
        'Voice',
        'Spotting errors',
        'Sentence improvement',
      ),
      chapter(
        'Vocabulary',
        'Synonyms and antonyms',
        'One word substitution',
        'Idioms and phrases',
        'Spelling correction',
        'Homonyms',
      ),
      chapter(
        'Comprehension and Usage',
        'Reading comprehension',
        'Cloze test',
        'Para jumbles',
        'Fill in the blanks',
        'Sentence rearrangement',
      ),
    ),
    subject(
      'General Awareness',
      chapter(
        'History',
        'Ancient India',
        'Medieval India',
        'Modern India and the freedom struggle',
      ),
      chapter(
        'Geography',
        'Physical geography of India and the world',
        'Indian rivers, soils and climate',
        'Economic geography and resources',
      ),
      chapter(
        'Polity',
        'Indian Constitution and its features',
        'Fundamental rights and duties',
        'Parliament, judiciary and executive',
        'Constitutional bodies',
      ),
      chapter(
        'Economics',
        'Basic economic concepts',
        'Indian economy and planning',
        'Banking and monetary policy',
        'Budget and taxation',
      ),
      chapter(
        'General Science',
        'Physics fundamentals',
        'Chemistry fundamentals',
        'Biology and human body',
        'Science and technology in the news',
      ),
      chapter(
        'Static and Current Affairs',
        'Books and authors',
        'Awards and honours',
        'Sports',
        'Important days and events',
        'Schemes and reports',
      ),
    ),
    subject(
      'Tier 2: Computer Knowledge and Statistics',
      chapter(
        'Computer Proficiency',
        'Computer basics and organisation',
        'Software and operating systems',
        'MS Office fundamentals',
        'Internet, WWW and email',
        'Networking and cyber security',
      ),
      chapter(
        'Statistics: Collection and Presentation',
        'Primary and secondary data',
        'Classification and tabulation',
        'Diagrammatic and graphical presentation',
      ),
      chapter(
        'Statistics: Measures and Distributions',
        'Measures of central tendency',
        'Measures of dispersion',
        'Moments, skewness and kurtosis',
        'Correlation and regression',
        'Probability theory and distributions',
        'Sampling theory',
        'Index numbers',
        'Time series analysis',
      ),
      chapter(
        'Finance and Economics',
        'Fundamental principles of accounting',
        'Finance commission and its role',
        'Basic concepts of economics',
        'Theory of demand and supply',
        'Indian economy and economic reforms',
      ),
    ),
  ],
};

export const gateCsIt: SyllabusTemplate = {
  id: 'gate-cs-it',
  name: 'GATE CS & IT',
  description: 'All ten sections plus General Aptitude, in the order the paper lists them.',
  category: 'exam',
  source: 'GATE Computer Science and Information Technology syllabus, transcribed for PrepPilot.',
  verified: true,
  subjects: [
    subject(
      'Engineering Mathematics',
      chapter(
        'Discrete Mathematics: Propositional and First Order Logic',
        'Propositional logic',
        'First order logic',
        'Validity and satisfiability',
      ),
      chapter(
        'Discrete Mathematics: Sets, Relations and Functions',
        'Sets and relations',
        'Equivalence and partial orders',
        'Functions',
        'Lattices',
        'Groups',
      ),
      chapter(
        'Discrete Mathematics: Combinatorics',
        'Counting and recurrence relations',
        'Generating functions',
        'Pigeonhole principle',
        'Inclusion-exclusion',
      ),
      chapter(
        'Discrete Mathematics: Graph Theory',
        'Connectivity',
        'Matching and colouring',
        'Trees and spanning trees',
        'Planarity',
      ),
      chapter(
        'Linear Algebra',
        'Matrices and determinants',
        'System of linear equations',
        'Eigenvalues and eigenvectors',
        'LU decomposition',
      ),
      chapter(
        'Calculus',
        'Limits, continuity and differentiability',
        'Maxima and minima',
        'Mean value theorem',
        'Integration',
      ),
      chapter(
        'Probability and Statistics',
        'Random variables',
        'Uniform, normal, exponential, Poisson and binomial distributions',
        'Mean, median, mode and standard deviation',
        'Conditional probability and Bayes theorem',
      ),
    ),
    subject(
      'Digital Logic',
      chapter(
        'Boolean Algebra and Logic Gates',
        'Boolean algebra',
        'Logic gates',
        'Minimisation using K-maps',
      ),
      chapter(
        'Combinational Circuits',
        'Adders and subtractors',
        'Multiplexers and demultiplexers',
        'Encoders and decoders',
        'Comparators',
      ),
      chapter(
        'Sequential Circuits',
        'Latches and flip-flops',
        'Counters',
        'Shift registers',
        'Finite state machines',
      ),
      chapter(
        'Number Representations and Computer Arithmetic',
        'Fixed and floating point representation',
        'Integer arithmetic',
        'IEEE 754 standard',
      ),
    ),
    subject(
      'Computer Organisation and Architecture',
      chapter(
        'Machine Instructions and Addressing Modes',
        'Instruction formats',
        'Addressing modes',
        'Instruction set architecture',
      ),
      chapter(
        'ALU, Data Path and Control Unit',
        'Arithmetic logic unit',
        'Data path design',
        'Hardwired and microprogrammed control',
      ),
      chapter(
        'Instruction Pipelining',
        'Pipeline stages',
        'Structural, data and control hazards',
        'Hazard mitigation techniques',
      ),
      chapter(
        'Memory Hierarchy',
        'Cache memory and mapping techniques',
        'Cache performance',
        'Main memory',
        'Secondary storage',
      ),
      chapter('I/O Interface', 'Programmed I/O', 'Interrupt-driven I/O', 'Direct memory access'),
    ),
    subject(
      'Programming and Data Structures',
      chapter(
        'Programming in C',
        'Data types and operators',
        'Control structures',
        'Functions and scope',
        'Pointers',
        'Arrays and strings',
        'Structures and unions',
      ),
      chapter('Recursion', 'Recursive functions', 'Recursion versus iteration', 'Tail recursion'),
      chapter('Linear Data Structures', 'Arrays', 'Stacks', 'Queues', 'Linked lists'),
      chapter(
        'Trees',
        'Binary trees and traversals',
        'Binary search trees',
        'Balanced trees',
        'Heaps',
      ),
      chapter('Graphs', 'Graph representations', 'Graph traversals'),
    ),
    subject(
      'Algorithms',
      chapter(
        'Analysis of Algorithms',
        'Asymptotic notation',
        'Time and space complexity',
        'Recurrence relations and the master theorem',
      ),
      chapter(
        'Searching and Sorting',
        'Linear and binary search',
        'Bubble, insertion and selection sort',
        'Merge sort and quick sort',
        'Heap sort',
        'Lower bounds for sorting',
      ),
      chapter(
        'Algorithm Design Techniques',
        'Greedy algorithms',
        'Divide and conquer',
        'Dynamic programming',
      ),
      chapter(
        'Graph Algorithms',
        'Breadth first and depth first search',
        'Minimum spanning trees',
        'Shortest path algorithms',
      ),
    ),
    subject(
      'Theory of Computation',
      chapter(
        'Regular Languages and Finite Automata',
        'Deterministic and non-deterministic finite automata',
        'Regular expressions',
        'Closure properties',
        'Pumping lemma for regular languages',
        'Minimisation of automata',
      ),
      chapter(
        'Context-Free Languages and Pushdown Automata',
        'Context-free grammars',
        'Pushdown automata',
        'Normal forms',
        'Pumping lemma for context-free languages',
      ),
      chapter(
        'Regular and Context-Free Language Properties',
        'Closure and decidability properties',
        'Chomsky hierarchy',
      ),
      chapter(
        'Turing Machines and Undecidability',
        'Turing machines',
        'Recursive and recursively enumerable languages',
        'Undecidability and reductions',
      ),
    ),
    subject(
      'Compiler Design',
      chapter(
        'Lexical Analysis',
        'Role of the lexical analyser',
        'Tokens and lexemes',
        'Finite automata in lexical analysis',
      ),
      chapter(
        'Parsing',
        'Top-down parsing',
        'Bottom-up parsing',
        'LL, LR, SLR and LALR parsers',
        'Syntax trees',
      ),
      chapter(
        'Syntax Directed Translation',
        'Attribute grammars',
        'Syntax directed definitions',
        'Intermediate code generation',
      ),
      chapter(
        'Runtime Environments and Optimisation',
        'Runtime environments',
        'Local optimisation',
        'Data flow analysis',
        'Constant propagation and liveness analysis',
      ),
    ),
    subject(
      'Operating System',
      chapter(
        'Processes and Threads',
        'Processes and process states',
        'Threads',
        'Inter-process communication',
        'CPU scheduling algorithms',
      ),
      chapter(
        'Concurrency and Synchronisation',
        'Critical section problem',
        'Semaphores and mutexes',
        'Classical synchronisation problems',
      ),
      chapter(
        'Deadlock',
        'Necessary conditions',
        'Deadlock prevention and avoidance',
        'Deadlock detection and recovery',
        "Banker's algorithm",
      ),
      chapter(
        'Memory Management',
        'Contiguous allocation and paging',
        'Segmentation',
        'Virtual memory and demand paging',
        'Page replacement algorithms',
        'Thrashing',
      ),
      chapter(
        'File Systems',
        'File organisation and directory structure',
        'File allocation methods',
        'Disk scheduling',
      ),
    ),
    subject(
      'Databases',
      chapter(
        'ER Model and Relational Model',
        'Entity-relationship model',
        'Relational model and relational algebra',
        'Tuple calculus',
      ),
      chapter(
        'SQL',
        'Data definition and manipulation',
        'Joins and nested queries',
        'Aggregate functions',
        'Views and integrity constraints',
      ),
      chapter(
        'Database Design',
        'Functional dependencies',
        'Normal forms up to BCNF',
        'Decomposition and its properties',
      ),
      chapter(
        'File Organisation and Indexing',
        'File organisation',
        'B trees and B+ trees',
        'Hashing',
      ),
      chapter(
        'Transactions and Concurrency Control',
        'ACID properties',
        'Serialisability',
        'Concurrency control protocols',
        'Recovery techniques',
      ),
    ),
    subject(
      'Computer Networks',
      chapter(
        'Layering and Network Models',
        'Concept of layering',
        'OSI reference model',
        'TCP/IP protocol stack',
      ),
      chapter(
        'Data Link Layer',
        'Framing and error detection',
        'Media access control',
        'Ethernet bridging and switching',
      ),
      chapter(
        'Network Layer',
        'IPv4 and IPv6 addressing',
        'Subnetting and CIDR',
        'Routing protocols: shortest path, flooding, distance vector and link state',
        'Fragmentation',
        'ICMP, NAT and DHCP',
      ),
      chapter(
        'Transport Layer',
        'Flow control and congestion control',
        'UDP and TCP',
        'TCP connection management',
        'Sockets',
      ),
      chapter(
        'Application Layer',
        'DNS',
        'SMTP, HTTP and HTTPS',
        'FTP',
        'Basics of network security',
      ),
    ),
    subject(
      'General Aptitude',
      chapter(
        'Verbal Aptitude',
        'English grammar and word usage',
        'Sentence completion',
        'Reading comprehension',
        'Narrative sequencing',
      ),
      chapter(
        'Quantitative Aptitude',
        'Data interpretation',
        'Ratios, percentages and powers',
        'Mensuration and geometry',
        'Elementary statistics and probability',
      ),
      chapter(
        'Analytical Aptitude',
        'Logic and deduction',
        'Analogy',
        'Numerical relations and reasoning',
      ),
      chapter(
        'Spatial Aptitude',
        'Transformation of shapes',
        'Paper folding, cutting and patterns',
        'Assembling and grouping of shapes',
      ),
    ),
  ],
};

export const neetPg: SyllabusTemplate = {
  id: 'neet-pg',
  name: 'NEET PG',
  description: 'All 19 MBBS subjects, grouped pre-clinical, para-clinical and clinical.',
  category: 'exam',
  source: 'NBEMS NEET-PG information bulletin (MBBS curriculum), transcribed for PrepPilot.',
  verified: true,
  subjects: [
    subject(
      'Pre-Clinical: Anatomy',
      chapter(
        'General Anatomy and Histology',
        'General anatomical terminology',
        'Bones, joints and muscles',
        'General histology and epithelium',
        'Connective and muscular tissue',
      ),
      chapter(
        'Upper and Lower Limb',
        'Bones and joints of the limbs',
        'Brachial plexus',
        'Lumbosacral plexus',
        'Arterial supply and venous drainage',
        'Nerve injuries',
      ),
      chapter(
        'Thorax and Abdomen',
        'Thoracic wall and diaphragm',
        'Heart, lungs and mediastinum',
        'Abdominal wall and inguinal region',
        'Gastrointestinal tract and peritoneum',
        'Retroperitoneum and pelvis',
        'Perineum',
      ),
      chapter(
        'Head, Neck and Neuroanatomy',
        'Skull and cranial fossae',
        'Triangles of the neck',
        'Cranial nerves',
        'Brain and spinal cord',
        'Meninges and ventricular system',
        'Ascending and descending tracts',
      ),
      chapter(
        'Embryology and Genetics',
        'Gametogenesis and fertilisation',
        'Development of the systems',
        'Congenital anomalies',
        'Chromosomal and genetic disorders',
      ),
    ),
    subject(
      'Pre-Clinical: Physiology',
      chapter(
        'General Physiology and Blood',
        'Cell physiology and transport',
        'Body fluid compartments',
        'Blood composition and haemostasis',
        'Blood groups and immunity',
      ),
      chapter(
        'Nerve, Muscle and Cardiovascular System',
        'Nerve and muscle physiology',
        'Cardiac cycle and output',
        'ECG',
        'Regulation of blood pressure',
        'Regional circulation',
      ),
      chapter(
        'Respiratory and Renal Physiology',
        'Mechanics of breathing',
        'Gas transport and regulation of respiration',
        'Renal function and clearance',
        'Acid-base balance',
      ),
      chapter(
        'Gastrointestinal and Endocrine Physiology',
        'GI motility and secretions',
        'Digestion and absorption',
        'Hypothalamo-pituitary axis',
        'Thyroid, adrenal and pancreatic hormones',
        'Reproductive physiology',
      ),
      chapter(
        'Neurophysiology',
        'Sensory and motor systems',
        'Special senses',
        'Higher functions and EEG',
        'Autonomic nervous system',
      ),
    ),
    subject(
      'Pre-Clinical: Biochemistry',
      chapter(
        'Chemistry and Metabolism of Biomolecules',
        'Carbohydrate chemistry and metabolism',
        'Lipid chemistry and metabolism',
        'Amino acid and protein metabolism',
        'Nucleotide metabolism',
      ),
      chapter(
        'Enzymes and Bioenergetics',
        'Enzyme kinetics and regulation',
        'Coenzymes and isoenzymes',
        'Biological oxidation and electron transport chain',
      ),
      chapter(
        'Molecular Biology',
        'DNA replication, transcription and translation',
        'Regulation of gene expression',
        'Recombinant DNA technology and molecular diagnostics',
      ),
      chapter(
        'Nutrition and Clinical Biochemistry',
        'Vitamins and minerals',
        'Nutritional disorders',
        'Liver, kidney and thyroid function tests',
        'Acid-base and electrolyte disorders',
      ),
    ),
    subject(
      'Para-Clinical: Pathology',
      chapter(
        'General Pathology',
        'Cell injury and adaptation',
        'Inflammation and repair',
        'Haemodynamic disorders',
        'Immunopathology',
        'Neoplasia',
        'Genetic and environmental diseases',
      ),
      chapter(
        'Haematology',
        'Anaemias',
        'Leukaemias and lymphomas',
        'Bleeding disorders',
        'Blood banking and transfusion medicine',
      ),
      chapter(
        'Systemic Pathology',
        'Cardiovascular pathology',
        'Respiratory pathology',
        'Gastrointestinal and hepatobiliary pathology',
        'Renal pathology',
        'Endocrine pathology',
        'Neuropathology',
        'Musculoskeletal and skin pathology',
      ),
    ),
    subject(
      'Para-Clinical: Pharmacology',
      chapter(
        'General Pharmacology',
        'Pharmacokinetics',
        'Pharmacodynamics',
        'Adverse drug reactions and interactions',
        'Routes of administration',
      ),
      chapter(
        'Autonomic and Central Nervous System Drugs',
        'Cholinergic and adrenergic drugs',
        'Sedatives, hypnotics and anaesthetics',
        'Antiepileptics and antiparkinsonian drugs',
        'Antipsychotics and antidepressants',
        'Opioid analgesics',
      ),
      chapter(
        'Cardiovascular, Renal and Blood Drugs',
        'Antihypertensives',
        'Antianginal and antiarrhythmic drugs',
        'Diuretics',
        'Anticoagulants and antiplatelets',
        'Hypolipidaemic drugs',
      ),
      chapter(
        'Chemotherapy',
        'Antibacterial agents',
        'Antitubercular and antileprotic drugs',
        'Antifungal, antiviral and antimalarial drugs',
        'Anticancer drugs',
      ),
      chapter(
        'Endocrine, Autacoid and Miscellaneous Drugs',
        'Antidiabetic drugs',
        'Thyroid and corticosteroid drugs',
        'NSAIDs and antihistamines',
        'Drugs acting on the gastrointestinal and respiratory systems',
        'Toxicology and antidotes',
      ),
    ),
    subject(
      'Para-Clinical: Microbiology',
      chapter(
        'General Microbiology and Immunology',
        'Morphology and physiology of bacteria',
        'Sterilisation and disinfection',
        'Innate and adaptive immunity',
        'Hypersensitivity and autoimmunity',
        'Immunodeficiency and transplantation',
      ),
      chapter(
        'Bacteriology',
        'Gram positive and gram negative cocci',
        'Gram positive and gram negative bacilli',
        'Mycobacteria',
        'Spirochaetes, rickettsia and chlamydia',
      ),
      chapter(
        'Virology',
        'DNA and RNA viruses',
        'Hepatitis viruses',
        'HIV and retroviruses',
        'Emerging viral infections',
      ),
      chapter(
        'Mycology, Parasitology and Applied Microbiology',
        'Superficial and systemic mycoses',
        'Protozoal and helminthic infections',
        'Hospital acquired infections and infection control',
      ),
    ),
    subject(
      'Para-Clinical: Forensic Medicine and Toxicology',
      chapter(
        'Forensic Pathology',
        'Death and its causes',
        'Postmortem changes and time since death',
        'Identification of the living and the dead',
        'Autopsy techniques',
      ),
      chapter(
        'Injuries and Medico-legal Aspects',
        'Mechanical injuries',
        'Thermal, electrical and regional injuries',
        'Asphyxial deaths',
        'Sexual offences and infanticide',
      ),
      chapter(
        'Medical Jurisprudence and Ethics',
        'Courts and legal procedures',
        'Consent and professional negligence',
        'Medical ethics and the code of conduct',
      ),
      chapter(
        'Toxicology',
        'General principles of toxicology',
        'Corrosives, irritants and metallic poisons',
        'Neurotoxic and cardiotoxic poisons',
        'Drug dependence and abuse',
      ),
    ),
    subject(
      'Para-Clinical: Community Medicine',
      chapter(
        'Concepts of Health and Epidemiology',
        'Concept of health and disease',
        'Principles of epidemiology',
        'Study designs',
        'Screening for disease',
      ),
      chapter(
        'Biostatistics and Demography',
        'Measures of central tendency and dispersion',
        'Tests of significance',
        'Sampling',
        'Demographic cycle and family planning',
      ),
      chapter(
        'Communicable and Non-Communicable Diseases',
        'Epidemiology and control of communicable diseases',
        'Immunisation and the cold chain',
        'Non-communicable diseases and their control',
      ),
      chapter(
        'Health Programmes and Environment',
        'National health programmes',
        'Health planning and management',
        'Occupational health',
        'Environmental sanitation and water supply',
        'Nutrition and health',
      ),
    ),
    subject(
      'Clinical: General Medicine',
      chapter(
        'Cardiology',
        'Ischaemic heart disease',
        'Heart failure',
        'Valvular heart disease',
        'Arrhythmias',
        'Hypertension',
      ),
      chapter(
        'Respiratory Medicine',
        'Obstructive airway diseases',
        'Pneumonia and tuberculosis',
        'Interstitial lung disease',
        'Pleural effusion and pneumothorax',
      ),
      chapter(
        'Gastroenterology and Hepatology',
        'Peptic ulcer disease',
        'Inflammatory bowel disease',
        'Cirrhosis and portal hypertension',
        'Jaundice and hepatitis',
        'Pancreatitis',
      ),
      chapter(
        'Nephrology and Endocrinology',
        'Acute and chronic kidney disease',
        'Glomerular diseases',
        'Diabetes mellitus',
        'Thyroid and adrenal disorders',
      ),
      chapter(
        'Neurology and Haematology',
        'Stroke and seizures',
        'Neuromuscular disorders',
        'Meningitis and encephalitis',
        'Anaemias and haematological malignancies',
      ),
      chapter(
        'Infectious Diseases and Rheumatology',
        'Fever and tropical infections',
        'HIV and opportunistic infections',
        'Connective tissue disorders',
        'Vasculitides',
      ),
    ),
    subject(
      'Clinical: General Surgery',
      chapter(
        'General Surgical Principles',
        'Wound healing and surgical infections',
        'Fluid, electrolytes and nutrition',
        'Shock and trauma',
        'Burns',
        'Surgical audit and sutures',
      ),
      chapter(
        'Gastrointestinal Surgery',
        'Oesophagus and stomach',
        'Small and large intestine',
        'Appendix and anorectal conditions',
        'Hernias',
        'Acute abdomen',
      ),
      chapter(
        'Hepatobiliary, Pancreatic and Splenic Surgery',
        'Gall bladder and biliary tract',
        'Liver',
        'Pancreas',
        'Spleen',
      ),
      chapter(
        'Endocrine and Breast Surgery',
        'Thyroid and parathyroid',
        'Adrenal',
        'Breast diseases and carcinoma',
      ),
      chapter(
        'Urology and Vascular Surgery',
        'Urinary calculi and obstruction',
        'Prostate and bladder',
        'Testis and scrotum',
        'Arterial and venous disorders',
      ),
      chapter(
        'Oncology and Miscellaneous',
        'Principles of surgical oncology',
        'Skin and soft tissue tumours',
        'Transplantation',
        'Minimally invasive surgery',
      ),
    ),
    subject(
      'Clinical: Obstetrics and Gynaecology',
      chapter(
        'Basic Obstetrics',
        'Physiological changes in pregnancy',
        'Antenatal care',
        'Normal labour and its management',
        'Puerperium and lactation',
      ),
      chapter(
        'High-Risk Pregnancy',
        'Hypertensive disorders of pregnancy',
        'Antepartum and postpartum haemorrhage',
        'Diabetes in pregnancy',
        'Preterm labour and multiple pregnancy',
        'Rh incompatibility',
      ),
      chapter(
        'Gynaecology: Menstrual and Endocrine Disorders',
        'Abnormal uterine bleeding',
        'Amenorrhoea',
        'Polycystic ovary syndrome',
        'Menopause',
      ),
      chapter(
        'Gynaecological Oncology and Infections',
        'Cervical, uterine and ovarian tumours',
        'Screening for cervical cancer',
        'Genital tract infections',
      ),
      chapter(
        'Contraception and Infertility',
        'Contraceptive methods',
        'Medical termination of pregnancy',
        'Infertility and assisted reproduction',
      ),
    ),
    subject(
      'Clinical: Paediatrics',
      chapter(
        'Growth, Development and Nutrition',
        'Normal growth and development',
        'Developmental milestones',
        'Infant and young child feeding',
        'Protein energy malnutrition',
        'Vitamin deficiencies',
      ),
      chapter(
        'Neonatology',
        'Care of the normal newborn',
        'Neonatal resuscitation',
        'Neonatal jaundice and sepsis',
        'Low birth weight and prematurity',
      ),
      chapter(
        'Paediatric Infections and Immunisation',
        'Immunisation schedule',
        'Common childhood infections',
        'Tuberculosis in children',
      ),
      chapter(
        'Systemic Paediatrics',
        'Congenital heart disease',
        'Respiratory disorders in children',
        'Paediatric nephrology and haematology',
        'Genetic and metabolic disorders',
        'Paediatric neurology',
      ),
    ),
    subject(
      'Clinical: Otorhinolaryngology (ENT)',
      chapter(
        'Ear',
        'Anatomy and physiology of hearing',
        'Otitis media and its complications',
        'Deafness and hearing assessment',
        'Vertigo and disorders of the inner ear',
      ),
      chapter(
        'Nose and Paranasal Sinuses',
        'Epistaxis',
        'Rhinitis and nasal polyps',
        'Sinusitis and its complications',
        'Tumours of the nose and sinuses',
      ),
      chapter(
        'Throat, Larynx and Neck',
        'Tonsils and adenoids',
        'Laryngeal disorders and hoarseness',
        'Airway obstruction and tracheostomy',
        'Neck swellings and head and neck malignancy',
      ),
    ),
    subject(
      'Clinical: Ophthalmology',
      chapter(
        'Anterior Segment',
        'Conjunctiva and cornea',
        'Uvea and uveitis',
        'Cataract',
        'Glaucoma',
      ),
      chapter(
        'Posterior Segment and Neuro-ophthalmology',
        'Retina and retinal detachment',
        'Diabetic and hypertensive retinopathy',
        'Optic nerve disorders',
        'Visual field defects',
      ),
      chapter(
        'Refraction, Squint and Ocular Adnexa',
        'Errors of refraction',
        'Strabismus and amblyopia',
        'Eyelid, lacrimal and orbital disorders',
        'Ocular trauma and community ophthalmology',
      ),
    ),
    subject(
      'Clinical: Dermatology and Venereology',
      chapter(
        'Infections and Infestations',
        'Bacterial and viral skin infections',
        'Fungal infections',
        'Leprosy',
        'Scabies and pediculosis',
      ),
      chapter(
        'Papulosquamous and Vesiculobullous Disorders',
        'Psoriasis and lichen planus',
        'Pemphigus and pemphigoid',
        'Eczema and dermatitis',
      ),
      chapter(
        'Sexually Transmitted Infections and Miscellaneous',
        'Syphilis and gonorrhoea',
        'HIV and its cutaneous manifestations',
        'Acne and pigmentary disorders',
        'Hair and nail disorders',
      ),
    ),
    subject(
      'Clinical: Psychiatry',
      chapter(
        'Assessment and Classification',
        'Psychiatric history and mental state examination',
        'Classification systems',
        'Psychiatric emergencies',
      ),
      chapter(
        'Major Psychiatric Disorders',
        'Schizophrenia and psychotic disorders',
        'Mood disorders',
        'Anxiety, obsessive-compulsive and stress-related disorders',
        'Somatoform and dissociative disorders',
      ),
      chapter(
        'Substance Use, Child Psychiatry and Treatment',
        'Alcohol and substance use disorders',
        'Child and adolescent psychiatry',
        'Psychopharmacology',
        'Psychotherapies and electroconvulsive therapy',
      ),
    ),
    subject(
      'Clinical: Orthopaedics, Anaesthesia and Radiology',
      chapter(
        'Orthopaedics: Trauma',
        'Principles of fracture management',
        'Fractures of the upper limb',
        'Fractures of the lower limb',
        'Spinal injuries',
        'Complications of fractures',
      ),
      chapter(
        'Orthopaedics: Cold Cases',
        'Bone and joint infections',
        'Bone tumours',
        'Arthritis and degenerative disorders',
        'Congenital and metabolic bone disease',
      ),
      chapter(
        'Anaesthesia',
        'Preoperative assessment',
        'General and regional anaesthesia',
        'Airway management',
        'Monitoring and complications',
        'Critical care and pain management',
      ),
      chapter(
        'Radiodiagnosis',
        'Basics of X-ray, ultrasound, CT and MRI',
        'Radiological anatomy',
        'Common radiological signs',
        'Radiotherapy and nuclear medicine basics',
      ),
    ),
  ],
};
