import type { SyllabusTemplate } from '../template';
import { chapter, subject } from './builder';

/**
 * The ICAI Chartered Accountancy papers, under the New Scheme of Education and
 * Training in force since 2023.
 *
 * Subjects are the papers, because that is the unit a student sits and passes.
 * The group each paper belongs to is in its name: exemption is granted per
 * group, so a student needs to see at a glance which half of the exam a paper
 * counts towards.
 */

const SOURCE = 'ICAI New Scheme of Education and Training, transcribed for PrepPilot.';

export const caFoundation: SyllabusTemplate = {
  id: 'ca-foundation',
  name: 'CA Foundation',
  description: 'Accounting, Business Laws, Quantitative Aptitude and Business Economics.',
  category: 'exam',
  source: SOURCE,
  verified: true,
  subjects: [
    subject(
      'Paper 1: Accounting',
      chapter(
        'Theoretical Framework',
        'Meaning and scope of accounting',
        'Accounting concepts, principles and conventions',
        'Capital and revenue expenditure and receipts',
        'Contingent assets and liabilities',
        'Accounting policies',
        'Accounting standards',
      ),
      chapter(
        'Accounting Process',
        'Basic accounting procedures and journal entries',
        'Ledgers',
        'Trial balance',
        'Subsidiary books',
        'Cash book',
        'Rectification of errors',
      ),
      chapter(
        'Bank Reconciliation Statement',
        'Introduction and reasons for difference',
        'Preparation of a bank reconciliation statement',
      ),
      chapter(
        'Inventories',
        'Meaning and basis of inventory valuation',
        'Cost formulae',
        'Record keeping systems',
      ),
      chapter(
        'Depreciation and Amortisation',
        'Concepts and methods of computation',
        'Accounting treatment of depreciation',
        'Change in depreciation method',
      ),
      chapter(
        'Bills of Exchange and Promissory Notes',
        'Meaning and types of instruments',
        'Accounting treatment',
        'Accommodation bills',
      ),
      chapter(
        'Preparation of Final Accounts of Sole Proprietors',
        'Trading account',
        'Profit and loss account',
        'Balance sheet',
        'Adjustment entries',
      ),
      chapter(
        'Financial Statements of Not-for-Profit Organisations',
        'Receipts and payments account',
        'Income and expenditure account',
        'Balance sheet',
      ),
      chapter(
        'Accounts from Incomplete Records',
        'Single entry system',
        'Statement of affairs method',
        'Conversion method',
      ),
      chapter(
        'Partnership and LLP Accounts',
        'Final accounts of partnership firms',
        'Admission, retirement and death of a partner',
        'Treatment of goodwill',
        'Dissolution of partnership firms and LLPs',
      ),
      chapter(
        'Company Accounts',
        'Definition of shares and debentures',
        'Issue of shares and debentures',
        'Forfeiture of shares',
        'Redemption of preference shares and debentures',
        'Statement of profit and loss and balance sheet',
      ),
    ),
    subject(
      'Paper 2: Business Laws',
      chapter(
        'Indian Regulatory Framework',
        'Major regulatory bodies',
        'Ministry of Corporate Affairs',
        'SEBI, RBI and other regulators',
      ),
      chapter(
        'The Indian Contract Act, 1872',
        'Nature of contracts',
        'Consideration',
        'Other essential elements of a contract',
        'Performance of contract',
        'Breach of contract and remedies',
        'Contingent and quasi contracts',
        'Contract of indemnity and guarantee',
        'Bailment and pledge',
        'Agency',
      ),
      chapter(
        'The Sale of Goods Act, 1930',
        'Formation of the contract of sale',
        'Conditions and warranties',
        'Transfer of ownership and delivery of goods',
        'Unpaid seller and their rights',
      ),
      chapter(
        'The Indian Partnership Act, 1932',
        'General nature of partnership',
        'Rights and duties of partners',
        'Reconstitution of a firm',
        'Registration and dissolution of a firm',
      ),
      chapter(
        'The Limited Liability Partnership Act, 2008',
        'Introduction and characteristics',
        'Incorporation of an LLP',
        'Partners and their relations',
        'Conversion into an LLP',
      ),
      chapter(
        'The Companies Act, 2013',
        'Essential features of a company',
        'Types of companies',
        'Incorporation and its effects',
        'Memorandum and articles of association',
      ),
      chapter(
        'The Negotiable Instruments Act, 1881',
        'Meaning and characteristics of negotiable instruments',
        'Promissory note, bill of exchange and cheque',
        'Holder and holder in due course',
        'Negotiation and endorsement',
        'Dishonour of a negotiable instrument',
      ),
    ),
    subject(
      'Paper 3: Quantitative Aptitude',
      chapter(
        'Business Mathematics: Ratio, Proportion, Indices and Logarithms',
        'Ratio and proportion',
        'Laws of indices',
        'Logarithms and their properties',
      ),
      chapter(
        'Business Mathematics: Equations',
        'Linear, simultaneous and quadratic equations',
        'Applications in business and economics',
      ),
      chapter(
        'Business Mathematics: Linear Inequalities',
        'Linear inequalities in one and two variables',
        'Graphical solution',
      ),
      chapter(
        'Business Mathematics: Mathematics of Finance',
        'Simple and compound interest',
        'Effective rate of interest',
        'Annuities',
        'Present and future value',
        'Net present value and perpetuity',
      ),
      chapter(
        'Business Mathematics: Permutations and Combinations',
        'Basic concepts',
        'Permutations with restrictions',
        'Combinations and their applications',
      ),
      chapter(
        'Business Mathematics: Sequence and Series',
        'Arithmetic progression',
        'Geometric progression',
        'Sum of n terms and their applications',
      ),
      chapter(
        'Business Mathematics: Sets, Relations and Functions',
        'Set theory and Venn diagrams',
        'Relations and functions',
        'Basics of limits and continuity',
      ),
      chapter(
        'Business Mathematics: Calculus',
        'Differential calculus and its applications',
        'Integral calculus and its applications',
      ),
      chapter(
        'Logical Reasoning',
        'Number series, coding and decoding',
        'Direction tests',
        'Seating arrangements',
        'Blood relations',
      ),
      chapter(
        'Statistics: Statistical Representation of Data',
        'Diagrammatic representation',
        'Frequency distribution',
        'Graphical representation',
      ),
      chapter(
        'Statistics: Measures of Central Tendency and Dispersion',
        'Mean, median and mode',
        'Range and mean deviation',
        'Standard deviation and quartile deviation',
      ),
      chapter(
        'Statistics: Probability',
        'Independent and dependent events',
        'Bayes theorem',
        'Expected value',
      ),
      chapter(
        'Statistics: Theoretical Distributions',
        'Binomial distribution',
        'Poisson distribution',
        'Normal distribution',
      ),
      chapter(
        'Statistics: Correlation and Regression',
        'Scatter diagram',
        'Karl Pearson coefficient of correlation',
        'Rank correlation',
        'Regression lines and coefficients',
      ),
      chapter(
        'Statistics: Index Numbers',
        'Uses of index numbers',
        'Methods of construction',
        'Problems in construction',
      ),
    ),
    subject(
      'Paper 4: Business Economics',
      chapter(
        'Introduction to Business Economics',
        'Meaning and scope of business economics',
        'Basic problems of an economy',
        'Role of price mechanism',
      ),
      chapter(
        'Theory of Demand and Supply',
        'Law of demand and elasticity of demand',
        'Theory of consumer behaviour',
        'Law of supply and elasticity of supply',
        'Demand forecasting',
      ),
      chapter(
        'Theory of Production and Cost',
        'Factors of production',
        'Laws of production',
        'Producer’s equilibrium',
        'Concepts of cost and cost curves',
      ),
      chapter(
        'Price Determination in Different Markets',
        'Perfect competition',
        'Monopoly',
        'Monopolistic competition',
        'Oligopoly',
      ),
      chapter(
        'Business Cycles',
        'Meaning and phases',
        'Features and causes of business cycles',
        'Relevance in business decisions',
      ),
      chapter(
        'Determination of National Income',
        'Macroeconomic aggregates',
        'Measurement of national income',
        'Determination of national income',
      ),
      chapter(
        'Public Finance',
        'Fiscal functions',
        'Market failure',
        'Government interventions',
        'Fiscal policy',
      ),
      chapter(
        'Money Market',
        'Concept of money demand and supply',
        'Monetary policy',
        'Money multiplier',
      ),
      chapter(
        'International Trade',
        'Theories of international trade',
        'Trade policy',
        'Foreign exchange market',
        'Balance of payments',
        'International economic institutions',
      ),
      chapter(
        'Indian Economy',
        'Indian economy before and after 1991',
        'Current state of the Indian economy',
      ),
    ),
  ],
};

export const caIntermediate: SyllabusTemplate = {
  id: 'ca-intermediate',
  name: 'CA Intermediate',
  description: 'Both groups: six papers from Advanced Accounting to Strategic Management.',
  category: 'exam',
  source: SOURCE,
  verified: true,
  subjects: [
    subject(
      'Group I — Paper 1: Advanced Accounting',
      chapter(
        'Introduction to Accounting Standards',
        'Framework for preparation and presentation of financial statements',
        'Applicability of accounting standards',
      ),
      chapter(
        'Accounting Standards on Presentation and Disclosure',
        'AS 1 Disclosure of accounting policies',
        'AS 3 Cash flow statements',
        'AS 17 Segment reporting',
        'AS 18 Related party disclosures',
        'AS 20 Earnings per share',
        'AS 24 Discontinuing operations',
      ),
      chapter(
        'Accounting Standards on Assets',
        'AS 2 Valuation of inventories',
        'AS 10 Property, plant and equipment',
        'AS 13 Accounting for investments',
        'AS 16 Borrowing costs',
        'AS 19 Leases',
        'AS 26 Intangible assets',
        'AS 28 Impairment of assets',
      ),
      chapter(
        'Accounting Standards on Liabilities and Revenue',
        'AS 7 Construction contracts',
        'AS 9 Revenue recognition',
        'AS 15 Employee benefits',
        'AS 29 Provisions, contingent liabilities and contingent assets',
      ),
      chapter(
        'Company Accounts',
        'Redemption of preference shares',
        'Redemption of debentures',
        'Buy back of securities',
        'Managerial remuneration',
        'Preparation of financial statements',
      ),
      chapter(
        'Accounting for Branches and Departments',
        'Dependent and independent branches',
        'Foreign branches',
        'Departmental accounts',
      ),
      chapter(
        'Accounting for Not-for-Profit Organisations',
        'Preparation of financial statements',
        'Treatment of special items',
      ),
      chapter(
        'Amalgamation and Internal Reconstruction',
        'Amalgamation of companies',
        'Accounting for amalgamation',
        'Internal reconstruction',
      ),
      chapter(
        'Consolidated Financial Statements',
        'Concept of a holding company',
        'Consolidation of a single subsidiary',
        'Minority interest and goodwill',
      ),
    ),
    subject(
      'Group I — Paper 2: Corporate and Other Laws',
      chapter(
        'The Companies Act, 2013: Preliminary and Incorporation',
        'Definitions and important terms',
        'Incorporation of a company',
        'Memorandum and articles of association',
        'Doctrine of indoor management',
      ),
      chapter(
        'The Companies Act, 2013: Prospectus and Share Capital',
        'Prospectus and allotment of securities',
        'Share capital and debentures',
        'Acceptance of deposits',
      ),
      chapter(
        'The Companies Act, 2013: Charges, Management and Administration',
        'Registration of charges',
        'Management and administration',
        'Declaration and payment of dividend',
      ),
      chapter(
        'The Companies Act, 2013: Accounts, Audit and Directors',
        'Accounts of companies',
        'Audit and auditors',
        'Appointment and qualification of directors',
        'Meetings of the board and its powers',
      ),
      chapter(
        'The Limited Liability Partnership Act, 2008',
        'Incorporation and its effects',
        'Partners and their relations',
        'Conversion and winding up',
      ),
      chapter(
        'The General Clauses Act, 1897',
        'Important definitions',
        'General rules of construction',
        'Powers and functionaries',
      ),
      chapter(
        'Interpretation of Statutes',
        'Rules of interpretation of statutes',
        'Internal and external aids',
        'Rules of interpretation of deeds and documents',
      ),
      chapter(
        'The Foreign Exchange Management Act, 1999',
        'Broad structure of FEMA',
        'Current and capital account transactions',
        'Realisation and repatriation of foreign exchange',
      ),
    ),
    subject(
      'Group I — Paper 3: Taxation',
      chapter(
        'Income-tax: Basic Concepts',
        'Income-tax law: an introduction',
        'Concept of previous year and assessment year',
        'Charge of income-tax',
        'Residential status and scope of total income',
      ),
      chapter(
        'Income-tax: Heads of Income — Salaries',
        'Chargeability and basis of charge',
        'Allowances and perquisites',
        'Deductions from salary',
      ),
      chapter(
        'Income-tax: Heads of Income — House Property',
        'Chargeability and computation of annual value',
        'Deductions from income from house property',
      ),
      chapter(
        'Income-tax: Profits and Gains of Business or Profession',
        'Chargeability and admissible deductions',
        'Depreciation',
        'Expenses expressly disallowed',
        'Presumptive taxation',
      ),
      chapter(
        'Income-tax: Capital Gains and Other Sources',
        'Capital assets and transfer',
        'Computation of capital gains',
        'Exemptions',
        'Income from other sources',
      ),
      chapter(
        'Income-tax: Aggregation, Set-off and Deductions',
        'Clubbing of income',
        'Set-off and carry forward of losses',
        'Deductions from gross total income',
      ),
      chapter(
        'Income-tax: Computation and Compliance',
        'Computation of total income and tax liability',
        'Advance tax, TDS and TCS',
        'Filing of return of income',
        'Provisions for filing return in electronic form',
      ),
      chapter(
        'GST: Concept and Charge',
        'Concept of indirect taxes and GST',
        'Supply under GST',
        'Charge of GST and composition levy',
        'Exemptions from GST',
      ),
      chapter(
        'GST: Valuation, Credit and Compliance',
        'Time and value of supply',
        'Input tax credit',
        'Registration',
        'Tax invoice, credit and debit notes',
        'Payment of tax and returns',
      ),
    ),
    subject(
      'Group II — Paper 4: Cost and Management Accounting',
      chapter(
        'Introduction to Cost and Management Accounting',
        'Objectives and scope',
        'Cost concepts and classification',
        'Cost centre and cost unit',
        'Elements of cost',
      ),
      chapter(
        'Material Cost',
        'Procurement and storage of materials',
        'Inventory control techniques',
        'Valuation of material issues',
        'Treatment of losses',
      ),
      chapter(
        'Employee Cost and Direct Expenses',
        'Attendance and payroll procedures',
        'Labour turnover',
        'Systems of incentive schemes',
        'Direct expenses',
      ),
      chapter(
        'Overheads: Absorption Costing Method',
        'Classification and collection of overheads',
        'Allocation and apportionment',
        'Absorption of overheads',
        'Under and over absorption',
      ),
      chapter(
        'Activity Based Costing',
        'Concept and purpose',
        'Stages in activity based costing',
        'Cost drivers and cost pools',
      ),
      chapter(
        'Cost Sheet and Cost Accounting Systems',
        'Preparation of a cost sheet',
        'Integrated and non-integrated accounting systems',
        'Reconciliation of cost and financial accounts',
      ),
      chapter(
        'Methods of Costing',
        'Job and batch costing',
        'Contract costing',
        'Process and operation costing',
        'Joint products and by-products',
        'Service costing',
      ),
      chapter(
        'Standard Costing',
        'Setting of standards',
        'Material, labour and overhead variances',
        'Sales variances',
      ),
      chapter(
        'Marginal Costing',
        'Marginal cost and contribution',
        'Cost-volume-profit analysis',
        'Break-even analysis',
        'Decision making with marginal costing',
      ),
      chapter(
        'Budgets and Budgetary Control',
        'Concept of a budget',
        'Preparation of functional budgets',
        'Flexible budgets',
        'Zero-based budgeting',
      ),
    ),
    subject(
      'Group II — Paper 5: Auditing and Ethics',
      chapter(
        'Nature, Objective and Scope of Audit',
        'Meaning and objectives of an audit',
        'Inherent limitations',
        'Scope of audit',
        'Standards on auditing',
      ),
      chapter(
        'Audit Strategy, Planning and Programme',
        'Audit strategy',
        'Audit planning and programme',
        'Knowledge of the client’s business',
        'Materiality',
      ),
      chapter(
        'Risk Assessment and Internal Control',
        'Audit risk and its components',
        'Internal control system',
        'Evaluation of internal control',
        'Internal control questionnaire',
        'Internal audit',
      ),
      chapter(
        'Audit Evidence',
        'Nature and sources of audit evidence',
        'Audit procedures',
        'External confirmation',
        'Analytical procedures',
        'Written representations',
      ),
      chapter(
        'Audit of Items of Financial Statements',
        'Audit of assets and liabilities',
        'Audit of income and expenditure',
        'Verification and valuation',
      ),
      chapter(
        'Audit Documentation',
        'Concept of audit documentation',
        'Audit working papers',
        'Audit file and ownership',
      ),
      chapter(
        'Completion and Review',
        'Subsequent events',
        'Going concern',
        'Evaluation of misstatements',
      ),
      chapter(
        'Audit Report',
        'Forming an opinion',
        'Unmodified and modified opinions',
        'Emphasis of matter paragraph',
        'Reporting under the Companies Act',
      ),
      chapter(
        'Special Features of Audit of Different Entities',
        'Audit of banks',
        'Audit of non-corporate entities',
        'Audit of cooperative societies',
      ),
      chapter(
        'Ethics and Terms of Audit Engagements',
        'Fundamental principles of professional ethics',
        'Independence of auditors',
        'Threats and safeguards',
        'Terms of audit engagement',
      ),
    ),
    subject(
      'Group II — Paper 6: Financial Management and Strategic Management',
      chapter(
        'FM: Scope and Objectives of Financial Management',
        'Meaning and scope',
        'Profit maximisation and wealth maximisation',
        'Role of a finance executive',
      ),
      chapter(
        'FM: Types of Financing',
        'Sources of finance',
        'Venture capital and debt securitisation',
        'Lease financing',
        'International financing',
      ),
      chapter(
        'FM: Financial Analysis and Planning',
        'Ratio analysis',
        'Cash flow and funds flow analysis',
        'Financial planning',
      ),
      chapter(
        'FM: Cost of Capital',
        'Cost of debt, preference and equity',
        'Weighted average cost of capital',
        'Marginal cost of capital',
      ),
      chapter(
        'FM: Financing and Leverage Decisions',
        'Capital structure theories',
        'Operating and financial leverage',
        'EBIT-EPS analysis',
      ),
      chapter(
        'FM: Investment Decisions',
        'Capital budgeting techniques',
        'Payback period and discounted payback',
        'Net present value and internal rate of return',
        'Capital rationing',
      ),
      chapter(
        'FM: Dividend Decisions',
        'Types of dividend policies',
        'Walter and Gordon models',
        'Modigliani-Miller hypothesis',
      ),
      chapter(
        'FM: Management of Working Capital',
        'Concept and estimation of working capital',
        'Inventory, receivables and payables management',
        'Management of cash',
        'Financing of working capital',
      ),
      chapter(
        'SM: Introduction to Strategic Management',
        'Meaning and nature of strategic management',
        'Strategic levels in organisations',
        'Vision, mission, goals and objectives',
      ),
      chapter(
        'SM: Strategic Analysis — External Environment',
        'Macro environment analysis',
        'Industry and competitive analysis',
        "Porter's five forces model",
      ),
      chapter(
        'SM: Strategic Analysis — Internal Environment',
        'Core competencies',
        'Value chain analysis',
        'SWOT analysis',
        'Strategic drivers',
      ),
      chapter(
        'SM: Strategic Choices',
        'Corporate level strategies',
        'Business level strategies',
        'Ansoff’s product-market growth matrix',
        'BCG growth-share matrix',
      ),
      chapter(
        'SM: Strategy Implementation and Evaluation',
        'Strategic change and organisation structure',
        'Strategic control',
        'Strategy audit',
        'Business process reengineering',
      ),
    ),
  ],
};

export const caFinal: SyllabusTemplate = {
  id: 'ca-final',
  name: 'CA Final',
  description: 'Both groups: Financial Reporting through to Integrated Business Solutions.',
  category: 'exam',
  source: SOURCE,
  verified: true,
  subjects: [
    subject(
      'Group I — Paper 1: Financial Reporting',
      chapter(
        'Framework and Indian Accounting Standards',
        'Conceptual framework for financial reporting under Ind AS',
        'Application of Ind AS',
        'Roadmap for implementation',
      ),
      chapter(
        'Ind AS on Presentation of Financial Statements',
        'Ind AS 1 Presentation of financial statements',
        'Ind AS 7 Statement of cash flows',
        'Ind AS 34 Interim financial reporting',
        'Ind AS 8 Accounting policies, changes in estimates and errors',
      ),
      chapter(
        'Ind AS on Assets and Liabilities',
        'Ind AS 2 Inventories',
        'Ind AS 16 Property, plant and equipment',
        'Ind AS 38 Intangible assets',
        'Ind AS 36 Impairment of assets',
        'Ind AS 116 Leases',
        'Ind AS 37 Provisions, contingent liabilities and contingent assets',
      ),
      chapter(
        'Ind AS on Revenue and Employee Benefits',
        'Ind AS 115 Revenue from contracts with customers',
        'Ind AS 19 Employee benefits',
        'Ind AS 102 Share-based payment',
      ),
      chapter(
        'Ind AS on Financial Instruments',
        'Ind AS 32 Presentation',
        'Ind AS 109 Recognition and measurement',
        'Ind AS 107 Disclosures',
      ),
      chapter(
        'Consolidated Financial Statements',
        'Ind AS 110 Consolidated financial statements',
        'Ind AS 111 Joint arrangements',
        'Ind AS 28 Investments in associates and joint ventures',
        'Ind AS 103 Business combinations',
      ),
      chapter(
        'Other Reporting Requirements',
        'Integrated reporting',
        'Corporate social responsibility reporting',
        'Business responsibility and sustainability reporting',
      ),
    ),
    subject(
      'Group I — Paper 2: Advanced Financial Management',
      chapter(
        'Financial Policy and Corporate Strategy',
        'Strategic decision making framework',
        'Interface of financial policy and strategic management',
        'Balancing financial goals against sustainable growth',
      ),
      chapter(
        'Risk Management',
        'Identification of types of risk',
        'Evaluation of financial risks',
        'Value at risk',
        'Counter-party risk',
      ),
      chapter(
        'Advanced Capital Budgeting Decisions',
        'Current trends in capital budgeting',
        'Dealing with risk and uncertainty',
        'Sensitivity and scenario analysis',
        'Real options',
      ),
      chapter(
        'Security Analysis and Valuation',
        'Fundamental and technical analysis',
        'Bond valuation',
        'Equity valuation models',
        'Valuation of businesses',
      ),
      chapter(
        'Portfolio Management',
        'Portfolio theory and analysis',
        'Capital asset pricing model',
        'Arbitrage pricing theory',
        'Portfolio performance evaluation',
      ),
      chapter(
        'Securitisation and Mutual Funds',
        'Concept and benefits of securitisation',
        'Mechanics of securitisation',
        'Types and evaluation of mutual funds',
      ),
      chapter(
        'Derivatives Analysis and Valuation',
        'Forwards and futures',
        'Options and option pricing models',
        'Swaps',
        'Commodity derivatives',
      ),
      chapter(
        'Foreign Exchange Exposure and Risk Management',
        'Exchange rate determination',
        'Types of exposure',
        'Hedging currency risk',
        'Foreign exchange derivatives',
      ),
      chapter(
        'International Financial Management',
        'International capital budgeting',
        'International working capital management',
        'International sources of finance',
      ),
      chapter(
        'Corporate Valuation, Mergers and Acquisitions',
        'Approaches to valuation',
        'Merger and acquisition strategy',
        'Financial evaluation of a merger',
        'Corporate restructuring and demergers',
      ),
      chapter(
        'Startup Finance',
        'Sources of funding for startups',
        'Venture capital and angel investing',
        'Startup valuation',
      ),
    ),
    subject(
      'Group I — Paper 3: Advanced Auditing, Assurance and Professional Ethics',
      chapter(
        'Quality Control and Engagement Standards',
        'Standards on quality control',
        'Overview of engagement standards',
        'Guidance notes',
      ),
      chapter(
        'Audit Planning, Strategy and Execution',
        'Audit planning and materiality',
        'Risk assessment procedures',
        'Response to assessed risks',
      ),
      chapter(
        'Risk Assessment and Internal Control',
        'Evaluation of internal control',
        'Internal financial controls',
        'Reporting on internal financial controls',
      ),
      chapter(
        'Audit of Items of Financial Statements',
        'Audit of assets, liabilities, income and expenditure',
        'Related party transactions',
        'Going concern',
      ),
      chapter(
        'Audit Reports and Certificates',
        'Forming an opinion and reporting',
        'Modifications to the opinion',
        'Key audit matters',
        'Reporting under CARO',
      ),
      chapter(
        'Audit of Banks, Insurance and NBFCs',
        'Audit of banks',
        'Audit of insurance companies',
        'Audit of non-banking financial companies',
      ),
      chapter(
        'Audit of Public Sector Undertakings and Cooperatives',
        'Special features of a government audit',
        'Comptroller and Auditor General',
        'Audit of cooperative societies',
      ),
      chapter(
        'Internal Audit, Management and Operational Audit',
        'Internal audit and its scope',
        'Management audit',
        'Operational audit',
        'Due diligence and forensic accounting',
      ),
      chapter(
        'Digital Auditing and Assurance',
        'Audit in an automated environment',
        'Data analytics in audit',
        'Cyber security considerations',
      ),
      chapter(
        'Professional Ethics and Liabilities of Auditors',
        'Code of ethics',
        'The Chartered Accountants Act, 1949 and schedules',
        'Professional misconduct',
        'Disciplinary mechanism',
      ),
    ),
    subject(
      'Group II — Paper 4: Direct Tax Laws and International Taxation',
      chapter(
        'Basis of Charge and Residential Status',
        'Basic concepts',
        'Residence and scope of total income',
        'Incomes which do not form part of total income',
      ),
      chapter(
        'Heads of Income',
        'Salaries',
        'Income from house property',
        'Profits and gains of business or profession',
        'Capital gains',
        'Income from other sources',
      ),
      chapter(
        'Special Provisions and Company Taxation',
        'Taxation of companies',
        'Minimum alternate tax',
        'Taxation of firms, LLPs and AOPs',
        'Taxation of trusts and charitable institutions',
      ),
      chapter(
        'Assessment, Appeals and Penalties',
        'Return of income and assessment procedure',
        'Appeals and revision',
        'Penalties and prosecution',
        'Settlement and dispute resolution',
      ),
      chapter(
        'Tax Deduction, Collection and Recovery',
        'Deduction of tax at source',
        'Collection of tax at source',
        'Advance tax and interest',
        'Refunds',
      ),
      chapter(
        'Tax Planning and Anti-Avoidance',
        'Tax planning, avoidance and evasion',
        'General anti-avoidance rules',
        'Specific anti-avoidance measures',
      ),
      chapter(
        'International Taxation: Transfer Pricing',
        'Associated enterprises and international transactions',
        'Arm’s length price and methods',
        'Documentation and country-by-country reporting',
        'Advance pricing agreements',
      ),
      chapter(
        'International Taxation: Non-Residents and Treaties',
        'Taxation of non-residents',
        'Double taxation relief',
        'Model tax conventions',
        'Application and interpretation of tax treaties',
        'Base erosion and profit shifting',
      ),
    ),
    subject(
      'Group II — Paper 5: Indirect Tax Laws',
      chapter(
        'GST: Levy and Collection',
        'Constitutional aspects and framework',
        'Supply under GST',
        'Charge of GST and reverse charge',
        'Composition levy',
        'Exemptions',
      ),
      chapter(
        'GST: Place, Time and Value of Supply',
        'Place of supply of goods and services',
        'Time of supply',
        'Value of supply and valuation rules',
      ),
      chapter(
        'GST: Input Tax Credit',
        'Eligibility and conditions',
        'Apportionment of credit and blocked credits',
        'Input service distributor',
        'Job work',
      ),
      chapter(
        'GST: Registration and Documentation',
        'Persons liable for registration',
        'Procedure for registration',
        'Tax invoice, credit and debit notes',
        'E-way bill',
      ),
      chapter(
        'GST: Returns, Payment and Refunds',
        'Payment of tax, interest and penalty',
        'Returns under GST',
        'Refunds',
        'Tax deduction and collection at source',
      ),
      chapter(
        'GST: Assessment, Audit and Appeals',
        'Assessment and audit',
        'Inspection, search, seizure and arrest',
        'Demands and recovery',
        'Appeals and revision',
        'Advance ruling',
        'Offences and penalties',
      ),
      chapter(
        'Customs: Levy and Valuation',
        'Levy of and exemptions from customs duty',
        'Types of duties',
        'Classification of goods',
        'Valuation under the Customs Act',
      ),
      chapter(
        'Customs: Procedures and Foreign Trade Policy',
        'Importation and exportation procedures',
        'Warehousing',
        'Duty drawback',
        'Foreign trade policy and export promotion schemes',
      ),
    ),
    subject(
      'Group II — Paper 6: Integrated Business Solutions',
      chapter(
        'Corporate and Economic Laws',
        'The Companies Act, 2013',
        'Securities laws',
        'The Insolvency and Bankruptcy Code',
        'FEMA and PMLA',
      ),
      chapter(
        'Strategic Cost and Performance Management',
        'Strategic cost management',
        'Decision making',
        'Performance evaluation and reporting',
        'Divisional transfer pricing',
      ),
      chapter(
        'Financial Reporting and Advanced Financial Management',
        'Application of Ind AS to case scenarios',
        'Valuation and financing decisions',
        'Risk management in practice',
      ),
      chapter(
        'Audit, Ethics and Direct Tax',
        'Assurance in a multidisciplinary case',
        'Professional ethics in practice',
        'Direct tax planning in a business context',
      ),
      chapter(
        'Indirect Tax and Multidisciplinary Case Studies',
        'GST in a business context',
        'Customs and foreign trade in practice',
        'Integrated case study practice',
      ),
    ),
  ],
};
