import type { SyllabusTemplate } from '../template';
import { chapter, subject } from './builder';

/**
 * Multi-year programmes rather than single examinations.
 *
 * MBBS is organised by professional year because that is how it is taught and
 * examined; DevOps has no awarding body at all, so it is organised by the
 * competencies a practitioner is hired for.
 */

export const mbbs: SyllabusTemplate = {
  id: 'mbbs',
  name: 'MBBS',
  description: 'All three professional phases, from the Foundation Course to the final year.',
  category: 'school',
  source: 'NMC Competency-Based Medical Education curriculum, transcribed for PrepPilot.',
  verified: true,
  subjects: [
    subject(
      'Phase I: Foundation Course',
      chapter(
        'Orientation',
        'The medical profession and the health care system',
        'National health priorities',
        'Medical ethics and professionalism',
        'Learning skills and time management',
      ),
      chapter(
        'Skills and Communication',
        'Basic life support',
        'Communication skills',
        'Computer and information literacy',
        'Language and language laboratory',
      ),
      chapter(
        'Field Visits and Sports',
        'Community health visits',
        'Sports and extracurricular activities',
      ),
    ),
    subject(
      'Phase I: Human Anatomy',
      chapter(
        'General Anatomy',
        'Terminology and anatomical position',
        'Bones, joints, muscles and fasciae',
        'Cardiovascular, lymphatic and nervous system overview',
        'Skin and its appendages',
      ),
      chapter(
        'Gross Anatomy: Limbs',
        'Upper limb',
        'Lower limb',
        'Joints of the limbs',
        'Nerve supply and nerve injuries',
      ),
      chapter(
        'Gross Anatomy: Thorax and Abdomen',
        'Thoracic wall, pleura and lungs',
        'Heart and great vessels',
        'Abdominal wall and inguinal region',
        'Abdominal viscera and peritoneum',
        'Pelvis and perineum',
      ),
      chapter(
        'Gross Anatomy: Head and Neck',
        'Scalp, face and cranial cavity',
        'Triangles of the neck',
        'Oral cavity, pharynx and larynx',
        'Orbit and ear',
        'Cranial nerves',
      ),
      chapter(
        'Neuroanatomy',
        'Spinal cord and brainstem',
        'Cerebrum and cerebellum',
        'Meninges, ventricles and blood supply',
        'Ascending and descending tracts',
        'Special senses pathways',
      ),
      chapter(
        'Histology',
        'Cell and epithelium',
        'Connective, muscular and nervous tissue',
        'Histology of the systems',
      ),
      chapter(
        'Embryology and Genetics',
        'Gametogenesis and fertilisation',
        'Embryonic and fetal development',
        'Development of the organ systems',
        'Congenital anomalies',
        'Principles of medical genetics',
      ),
    ),
    subject(
      'Phase I: Physiology',
      chapter(
        'General Physiology',
        'Cell and transport across membranes',
        'Homeostasis and body fluid compartments',
        'Membrane potentials',
      ),
      chapter(
        'Haematology',
        'Blood composition and plasma proteins',
        'Red and white blood cells',
        'Haemostasis and coagulation',
        'Blood groups and transfusion',
      ),
      chapter(
        'Nerve-Muscle Physiology',
        'Structure and function of neurons',
        'Nerve conduction',
        'Neuromuscular junction',
        'Skeletal, cardiac and smooth muscle',
      ),
      chapter(
        'Cardiovascular System',
        'Cardiac cycle and cardiac output',
        'Electrocardiogram',
        'Regulation of blood pressure',
        'Regional and coronary circulation',
        'Cardiovascular responses to exercise and haemorrhage',
      ),
      chapter(
        'Respiratory System',
        'Mechanics of ventilation',
        'Pulmonary function tests',
        'Transport of gases',
        'Regulation of respiration',
        'Hypoxia and applied respiratory physiology',
      ),
      chapter(
        'Gastrointestinal System',
        'Secretions of the gastrointestinal tract',
        'Motility',
        'Digestion and absorption',
        'Liver and gall bladder function',
      ),
      chapter(
        'Renal System',
        'Glomerular filtration and tubular function',
        'Concentration and dilution of urine',
        'Acid-base balance',
        'Micturition and renal function tests',
      ),
      chapter(
        'Endocrine and Reproductive System',
        'Hypothalamo-pituitary axis',
        'Thyroid, parathyroid and adrenal glands',
        'Endocrine pancreas',
        'Male and female reproductive physiology',
        'Pregnancy and lactation',
      ),
      chapter(
        'Neurophysiology and Special Senses',
        'Sensory and motor systems',
        'Reflexes and posture',
        'Hypothalamus and limbic system',
        'Higher functions, sleep and EEG',
        'Vision, hearing, taste and smell',
      ),
    ),
    subject(
      'Phase I: Biochemistry',
      chapter(
        'Molecules and Enzymes',
        'Chemistry of carbohydrates, lipids and proteins',
        'Enzymes and enzyme kinetics',
        'Vitamins and coenzymes',
      ),
      chapter(
        'Metabolism',
        'Carbohydrate metabolism',
        'Lipid metabolism',
        'Amino acid metabolism',
        'Integration of metabolism',
        'Biological oxidation',
      ),
      chapter(
        'Molecular Biology',
        'Structure of nucleic acids',
        'Replication, transcription and translation',
        'Regulation of gene expression',
        'Molecular techniques in medicine',
      ),
      chapter(
        'Clinical and Nutritional Biochemistry',
        'Nutrition and energy metabolism',
        'Mineral metabolism',
        'Organ function tests',
        'Acid-base and electrolyte balance',
        'Free radicals and antioxidants',
      ),
    ),
    subject(
      'Phase II: Pathology',
      chapter(
        'General Pathology',
        'Cell injury, adaptation and cell death',
        'Acute and chronic inflammation',
        'Tissue repair and healing',
        'Haemodynamic disorders and shock',
        'Neoplasia',
        'Immunopathology',
      ),
      chapter(
        'Haematology',
        'Anaemia and its classification',
        'Leukaemia and lymphoma',
        'Bleeding and coagulation disorders',
        'Transfusion medicine',
      ),
      chapter(
        'Systemic Pathology',
        'Cardiovascular and respiratory pathology',
        'Gastrointestinal and hepatobiliary pathology',
        'Renal and urinary tract pathology',
        'Endocrine and reproductive pathology',
        'Central nervous system and musculoskeletal pathology',
      ),
      chapter(
        'Laboratory Medicine',
        'Clinical pathology and urine examination',
        'Cytopathology',
        'Autopsy pathology',
      ),
    ),
    subject(
      'Phase II: Microbiology',
      chapter(
        'General Microbiology',
        'Bacterial morphology and physiology',
        'Sterilisation and disinfection',
        'Culture media and identification',
        'Antimicrobial resistance',
      ),
      chapter(
        'Immunology',
        'Innate and adaptive immunity',
        'Antigen and antibody reactions',
        'Hypersensitivity reactions',
        'Autoimmunity and immunodeficiency',
      ),
      chapter(
        'Systematic Bacteriology',
        'Gram positive and gram negative organisms',
        'Mycobacteria',
        'Anaerobes and spirochaetes',
      ),
      chapter(
        'Virology, Mycology and Parasitology',
        'DNA and RNA viruses',
        'Hepatitis viruses and HIV',
        'Medical mycology',
        'Protozoa and helminths',
      ),
      chapter(
        'Applied Microbiology',
        'Hospital acquired infection and infection control',
        'Specimen collection and laboratory diagnosis',
        'Biomedical waste management',
      ),
    ),
    subject(
      'Phase II: Pharmacology',
      chapter(
        'General Pharmacology',
        'Pharmacokinetics and pharmacodynamics',
        'Routes of drug administration',
        'Adverse drug reactions and pharmacovigilance',
        'Drug interactions',
        'Rational prescribing and essential medicines',
      ),
      chapter(
        'Autonomic Nervous System',
        'Cholinergic and anticholinergic drugs',
        'Adrenergic and antiadrenergic drugs',
        'Autacoids and related drugs',
      ),
      chapter(
        'Central Nervous System',
        'General and local anaesthetics',
        'Sedative-hypnotics and antiepileptics',
        'Antiparkinsonian drugs',
        'Antipsychotics, antidepressants and lithium',
        'Opioid and non-opioid analgesics',
      ),
      chapter(
        'Cardiovascular, Renal and Haematological Drugs',
        'Antihypertensive and antianginal drugs',
        'Drugs for heart failure and arrhythmias',
        'Diuretics',
        'Anticoagulants, antiplatelets and thrombolytics',
        'Hypolipidaemic drugs and haematinics',
      ),
      chapter(
        'Chemotherapy',
        'General principles of antimicrobial therapy',
        'Beta-lactams and other antibacterials',
        'Antitubercular and antileprotic drugs',
        'Antifungal, antiviral and antiretroviral drugs',
        'Antimalarial and anthelmintic drugs',
        'Anticancer and immunosuppressant drugs',
      ),
      chapter(
        'Endocrine, Gastrointestinal and Respiratory Drugs',
        'Corticosteroids and thyroid drugs',
        'Insulin and oral hypoglycaemics',
        'Drugs for peptic ulcer and emesis',
        'Drugs for asthma and COPD',
        'Toxicology and antidotes',
      ),
    ),
    subject(
      'Phase III Part I: Forensic Medicine and Toxicology',
      chapter(
        'Forensic Pathology',
        'Death, its types and postmortem changes',
        'Identification',
        'Autopsy and exhumation',
      ),
      chapter(
        'Clinical Forensic Medicine',
        'Mechanical, thermal and regional injuries',
        'Asphyxial deaths',
        'Sexual offences',
        'Infant deaths and infanticide',
      ),
      chapter(
        'Medical Jurisprudence',
        'Legal procedures and court testimony',
        'Consent, negligence and professional misconduct',
        'Medical ethics and relevant acts',
      ),
      chapter(
        'Toxicology',
        'General principles and management of poisoning',
        'Corrosive, irritant and metallic poisons',
        'Neurotoxic, cardiotoxic and asphyxiant poisons',
        'Drug dependence and abuse',
      ),
    ),
    subject(
      'Phase III Part I: Community Medicine',
      chapter(
        'Concepts of Health, Disease and Epidemiology',
        'Concept of health and disease',
        'Natural history of disease and levels of prevention',
        'Principles and methods of epidemiology',
        'Epidemiological study designs',
        'Screening and surveillance',
      ),
      chapter(
        'Biostatistics and Demography',
        'Data collection and presentation',
        'Measures of central tendency and dispersion',
        'Tests of significance and sampling',
        'Demography and family planning',
        'Population dynamics',
      ),
      chapter(
        'Communicable Diseases',
        'Epidemiology and control of respiratory infections',
        'Intestinal and arthropod-borne infections',
        'Zoonoses and surface infections',
        'Immunisation and the cold chain',
      ),
      chapter(
        'Non-Communicable Diseases and Health Programmes',
        'Epidemiology of non-communicable diseases',
        'National health programmes',
        'Health planning, management and economics',
        'Health care delivery in India',
      ),
      chapter(
        'Environment, Nutrition and Occupational Health',
        'Water, air and waste management',
        'Nutrition and nutritional programmes',
        'Occupational health hazards',
        'Maternal and child health',
        'Disaster management',
      ),
    ),
    subject(
      'Phase III Part I: Otorhinolaryngology and Ophthalmology',
      chapter(
        'ENT: Ear',
        'Anatomy and physiology of the ear',
        'Otitis externa and otitis media',
        'Deafness and hearing tests',
        'Vertigo and facial nerve palsy',
      ),
      chapter(
        'ENT: Nose and Sinuses',
        'Epistaxis and nasal obstruction',
        'Rhinitis, polyps and sinusitis',
        'Nasal and sinus tumours',
      ),
      chapter(
        'ENT: Throat, Larynx and Neck',
        'Diseases of the tonsils and pharynx',
        'Laryngeal disorders and stridor',
        'Tracheostomy and airway emergencies',
        'Head and neck tumours',
      ),
      chapter(
        'Ophthalmology: Anterior Segment',
        'Conjunctival and corneal disorders',
        'Uveitis',
        'Cataract and its management',
        'Glaucoma',
      ),
      chapter(
        'Ophthalmology: Posterior Segment and Refraction',
        'Retinal disorders',
        'Optic nerve and visual pathway',
        'Errors of refraction and squint',
        'Ocular trauma and community ophthalmology',
      ),
    ),
    subject(
      'Phase III Part II: General Medicine',
      chapter(
        'Clinical Approach',
        'History taking and physical examination',
        'Symptom-based approach',
        'Interpretation of common investigations',
      ),
      chapter(
        'Cardiovascular and Respiratory Medicine',
        'Ischaemic heart disease and heart failure',
        'Valvular and congenital heart disease',
        'Hypertension and arrhythmias',
        'Asthma, COPD and pneumonia',
        'Tuberculosis and pleural disease',
      ),
      chapter(
        'Gastroenterology, Hepatology and Nephrology',
        'Peptic ulcer and inflammatory bowel disease',
        'Liver disease, jaundice and cirrhosis',
        'Acute and chronic kidney disease',
        'Glomerular and tubular disorders',
      ),
      chapter(
        'Endocrinology, Haematology and Rheumatology',
        'Diabetes mellitus and its complications',
        'Thyroid and adrenal disease',
        'Anaemias and haematological malignancies',
        'Connective tissue disorders and vasculitis',
      ),
      chapter(
        'Neurology, Infectious Disease and Emergencies',
        'Stroke, seizures and headache',
        'Infections of the nervous system',
        'Fever and tropical infections',
        'HIV medicine',
        'Poisoning and medical emergencies',
      ),
    ),
    subject(
      'Phase III Part II: General Surgery',
      chapter(
        'Basic Surgical Principles',
        'Wound healing and surgical infection',
        'Fluid, electrolyte and nutritional management',
        'Shock, trauma and burns',
        'Blood transfusion and surgical audit',
      ),
      chapter(
        'Gastrointestinal and Hepatobiliary Surgery',
        'Oesophagus, stomach and duodenum',
        'Small and large bowel',
        'Appendix, anus and rectum',
        'Hernias and the acute abdomen',
        'Liver, gall bladder, pancreas and spleen',
      ),
      chapter(
        'Endocrine, Breast and Oncological Surgery',
        'Thyroid and parathyroid surgery',
        'Breast disease and carcinoma',
        'Principles of surgical oncology',
        'Skin and soft tissue swellings',
      ),
      chapter(
        'Urology and Vascular Surgery',
        'Urolithiasis and obstructive uropathy',
        'Prostate, bladder and renal tumours',
        'Scrotal and testicular conditions',
        'Arterial, venous and lymphatic disorders',
      ),
      chapter(
        'Orthopaedics',
        'Principles of fracture management',
        'Fractures and dislocations by region',
        'Bone and joint infections',
        'Bone tumours and metabolic bone disease',
        'Arthritis and spinal disorders',
      ),
    ),
    subject(
      'Phase III Part II: Obstetrics and Gynaecology',
      chapter(
        'Basic Obstetrics',
        'Anatomy and physiology of pregnancy',
        'Diagnosis of pregnancy and antenatal care',
        'Normal labour and delivery',
        'Puerperium, lactation and newborn care',
      ),
      chapter(
        'Complicated Pregnancy and Labour',
        'Hypertensive disorders and eclampsia',
        'Antepartum and postpartum haemorrhage',
        'Medical disorders in pregnancy',
        'Malpresentations and obstructed labour',
        'Operative obstetrics',
      ),
      chapter(
        'Gynaecology',
        'Menstrual disorders and abnormal uterine bleeding',
        'Genital tract infections',
        'Benign and malignant gynaecological tumours',
        'Prolapse and urogynaecology',
        'Menopause',
      ),
      chapter(
        'Reproductive Medicine and Family Welfare',
        'Infertility and its management',
        'Contraception',
        'Medical termination of pregnancy',
        'National family welfare programmes',
      ),
    ),
    subject(
      'Phase III Part II: Paediatrics and Allied Specialties',
      chapter(
        'Paediatrics: Growth, Development and Nutrition',
        'Normal growth and development',
        'Assessment of growth',
        'Infant and young child feeding',
        'Malnutrition and micronutrient deficiencies',
      ),
      chapter(
        'Paediatrics: Neonatology and Systemic Disease',
        'Care of the newborn and resuscitation',
        'Neonatal jaundice, sepsis and prematurity',
        'Congenital heart disease',
        'Respiratory, renal and neurological disorders in children',
        'Genetic and metabolic disorders',
      ),
      chapter(
        'Dermatology and Venereology',
        'Common skin infections and infestations',
        'Papulosquamous and vesiculobullous disorders',
        'Leprosy',
        'Sexually transmitted infections',
      ),
      chapter(
        'Psychiatry',
        'Psychiatric assessment and classification',
        'Psychotic and mood disorders',
        'Anxiety and stress-related disorders',
        'Substance use disorders',
        'Psychopharmacology and psychotherapy',
      ),
      chapter(
        'Anaesthesia and Radiodiagnosis',
        'Preoperative assessment and general anaesthesia',
        'Regional anaesthesia and pain management',
        'Critical care and resuscitation',
        'Basics of imaging modalities',
        'Common radiological diagnoses',
      ),
    ),
  ],
};

export const devops: SyllabusTemplate = {
  id: 'devops',
  name: 'DevOps',
  description: 'From Linux and Git through CI/CD, containers, cloud and observability.',
  category: 'custom',
  source: 'Assembled from widely used DevOps role and certification competencies.',
  verified: true,
  subjects: [
    subject(
      'Foundations: Linux, Networking and Scripting',
      chapter(
        'Linux Fundamentals',
        'Filesystem hierarchy and navigation',
        'File permissions and ownership',
        'Users, groups and sudo',
        'Package management',
        'Systemd and service management',
        'Process management and signals',
        'Logs and journald',
      ),
      chapter(
        'Shell Scripting',
        'Bash syntax and variables',
        'Conditionals and loops',
        'Functions and arguments',
        'Text processing with grep, sed and awk',
        'Exit codes and error handling',
        'Cron and scheduled jobs',
      ),
      chapter(
        'Networking',
        'OSI and TCP/IP models',
        'IP addressing and subnetting',
        'DNS and name resolution',
        'HTTP and HTTPS',
        'TLS and certificates',
        'Firewalls and security groups',
        'Load balancing concepts',
        'Troubleshooting with dig, curl, netstat and tcpdump',
      ),
      chapter(
        'Programming for Automation',
        'Python basics for automation',
        'Working with APIs and JSON',
        'Virtual environments and dependency management',
        'Writing maintainable automation scripts',
      ),
    ),
    subject(
      'Source Control and Collaboration',
      chapter(
        'Git Fundamentals',
        'Repositories, commits and the staging area',
        'Branching and merging',
        'Rebasing and history rewriting',
        'Resolving conflicts',
        'Tags and releases',
        'Submodules and large file storage',
      ),
      chapter(
        'Collaboration Workflows',
        'Trunk-based development',
        'Git flow and GitHub flow',
        'Pull requests and code review',
        'Branch protection and required checks',
        'Conventional commits and semantic versioning',
      ),
      chapter(
        'Repository Automation',
        'Git hooks',
        'Issue and pull request templates',
        'CODEOWNERS',
        'Monorepo versus polyrepo trade-offs',
      ),
    ),
    subject(
      'Continuous Integration and Delivery',
      chapter(
        'CI Fundamentals',
        'Why continuous integration',
        'Build pipelines and stages',
        'Caching and build artefacts',
        'Fast feedback and pipeline duration',
        'Flaky tests and quarantine',
      ),
      chapter(
        'Pipeline Tooling',
        'GitHub Actions',
        'GitLab CI',
        'Jenkins pipelines',
        'Reusable workflows and shared libraries',
        'Self-hosted versus managed runners',
      ),
      chapter(
        'Testing in the Pipeline',
        'Unit, integration and end-to-end tests',
        'Static analysis and linting',
        'Code coverage gates',
        'Contract testing',
        'Performance and load testing',
      ),
      chapter(
        'Deployment Strategies',
        'Blue-green deployment',
        'Canary releases',
        'Rolling updates',
        'Feature flags',
        'Rollback and forward-fix',
        'Database migrations in a deployment',
      ),
      chapter(
        'Artefact and Release Management',
        'Artefact repositories',
        'Container registries',
        'Versioning and immutable artefacts',
        'Software supply chain and provenance',
      ),
    ),
    subject(
      'Containers and Orchestration',
      chapter(
        'Docker',
        'Images, layers and the build cache',
        'Writing a Dockerfile',
        'Multi-stage builds',
        'Volumes and bind mounts',
        'Container networking',
        'Docker Compose',
        'Image size and security scanning',
      ),
      chapter(
        'Kubernetes Core Objects',
        'Pods, ReplicaSets and Deployments',
        'Services and Ingress',
        'ConfigMaps and Secrets',
        'Namespaces and labels',
        'StatefulSets and DaemonSets',
        'Jobs and CronJobs',
      ),
      chapter(
        'Kubernetes Operations',
        'Scheduling, taints and tolerations',
        'Resource requests and limits',
        'Horizontal and vertical autoscaling',
        'Probes and health checks',
        'Rolling updates and rollbacks',
        'RBAC and service accounts',
        'Persistent volumes and storage classes',
      ),
      chapter(
        'Packaging and GitOps',
        'Helm charts and values',
        'Kustomize overlays',
        'Argo CD and Flux',
        'Declarative reconciliation',
        'Progressive delivery',
      ),
    ),
    subject(
      'Infrastructure as Code and Configuration',
      chapter(
        'Terraform',
        'Providers, resources and state',
        'Variables, outputs and locals',
        'Modules and composition',
        'Remote state and locking',
        'Plan, apply and drift detection',
        'Workspaces and environments',
      ),
      chapter(
        'Configuration Management',
        'Ansible inventories and playbooks',
        'Roles and reusable content',
        'Idempotency',
        'Secrets in configuration management',
      ),
      chapter(
        'Infrastructure Practice',
        'Immutable infrastructure',
        'Environment parity',
        'Policy as code',
        'Cost awareness and tagging',
        'Reviewing infrastructure changes',
      ),
    ),
    subject(
      'Cloud Platforms',
      chapter(
        'Cloud Fundamentals',
        'Shared responsibility model',
        'Regions and availability zones',
        'IAM: users, roles and policies',
        'Billing and cost management',
      ),
      chapter(
        'Compute and Storage',
        'Virtual machines and autoscaling groups',
        'Managed container services',
        'Serverless functions',
        'Object, block and file storage',
        'Content delivery networks',
      ),
      chapter(
        'Networking and Managed Services',
        'Virtual private clouds and subnets',
        'Load balancers and DNS',
        'Managed databases',
        'Message queues and event buses',
        'Secrets and key management',
      ),
      chapter(
        'Resilience and Architecture',
        'High availability patterns',
        'Backup and restore',
        'Disaster recovery: RTO and RPO',
        'Multi-region considerations',
      ),
    ),
    subject(
      'Observability and Reliability',
      chapter(
        'Monitoring and Metrics',
        'The four golden signals',
        'Prometheus and PromQL',
        'Grafana dashboards',
        'Instrumenting an application',
        'Alerting rules and thresholds',
      ),
      chapter(
        'Logging and Tracing',
        'Structured logging',
        'Log aggregation and retention',
        'Distributed tracing and spans',
        'OpenTelemetry',
        'Correlating logs, metrics and traces',
      ),
      chapter(
        'Site Reliability Engineering',
        'Service level indicators, objectives and agreements',
        'Error budgets',
        'Toil and automation',
        'Capacity planning',
        'Chaos engineering',
      ),
      chapter(
        'Incident Response',
        'On-call and escalation',
        'Incident command and communication',
        'Blameless postmortems',
        'Runbooks and playbooks',
      ),
    ),
    subject(
      'Security and Compliance (DevSecOps)',
      chapter(
        'Secure Software Supply Chain',
        'Dependency scanning and SBOM',
        'Container image scanning',
        'Signing and verifying artefacts',
        'Pinning and reproducible builds',
      ),
      chapter(
        'Secrets Management',
        'Never committing secrets',
        'Vault and cloud secret stores',
        'Secret rotation',
        'Workload identity and short-lived credentials',
      ),
      chapter(
        'Application and Platform Security',
        'OWASP Top Ten',
        'Static and dynamic application security testing',
        'Least privilege and network policy',
        'Hardening images and hosts',
      ),
      chapter(
        'Compliance and Governance',
        'Audit logging',
        'Change management and approvals',
        'Common frameworks: SOC 2 and ISO 27001',
        'Data protection and retention',
      ),
    ),
  ],
};
